// Choreography for the F-14D Super Tomcat (copied into the sidecar at build;
// the viewer's Animation tab is the only consumer).
//
// The aircraft has NO kinematics: nothing here is a joint. The whole thing is
// a staged separation, so it is choreography end to end and the model declares
// no mates at all.
//
// Two acts on one master ramp. Act 1 separates the ten systems; act 2 breaks
// the wings and the aft section into their own parts. Every stage is a WINDOW
// on the ramp with a smoothstep ease, so the eye gets a sequence rather than a
// single pop; the acts overlap on purpose (act 1 spans [0, 0.58] of the ramp,
// act 2 [0.52, 1]).
//
// Act-2 leaves are addressed by occurrence id because there is no name
// selector for "every slat track on both wings"; the lists are GENERATED by
// render/subrefs.py against the built assembly — do not hand-edit them. The
// o1.N numbering is by CHILD ORDER of what f14d.py actually built: three of
// the thirteen SYSTEMS have no module and take no number, so adding any of
// them renumbers everything after it and this file must be renumbered in the
// same commit.

const ACT1_END = 0.58;
const ACT2_START = 0.52;
const ACT2_SPAN = 1 - ACT2_START;

// system ref -> [[stage start, stage end] within act 1, explode vector in mm]
const SYSTEMS = {
  "o1.1": [[0.0, 0.55], [-1400, 0, 5200]], //  airframe   one blended loft
  "o1.2": [[0.10, 0.62], [-500, 0, 2500]], //  cockpit    tub, seats, canopy
  "o1.3": [[0.16, 0.68], [200, 0, 3300]], //   wings      panels, slats, flaps
  "o1.6": [[0.22, 0.74], [1900, 0, 2700]], //  empennage  fins, stabilators
  "o1.5": [[0.26, 0.78], [4400, 0, 300]], //   nozzles    C-D petals, seals
  "o1.7": [[0.32, 0.84], [2700, 0, -600]], //  aft        brakes, hook
  "o1.4": [[0.38, 0.88], [-1000, 0, -2500]], // inlets    ramps, ducts
  "o1.9": [[0.44, 0.92], [200, 0, -2300]], //  main_gear  legs, doors, bays
  "o1.8": [[0.48, 0.96], [-1900, 0, -1700]], // nose_gear leg, launch bar
  "o1.10": [[0.52, 1.00], [0, 0, 1500]] //     details    antennas, lights
};

// subassembly -> [[stage window within act 2], ADDITIVE explode vector].
// These ride ON TOP of their system's act-1 travel, so the wing parts keep
// travelling with the wing while separating from it.
//
// Anything mirrored port/stbd is its own group: one ref moves every occurrence
// it names by the SAME vector, so a single "wingtips" group would push the
// port tip outboard and the starboard tip straight through the wing.
const SUBS = [
  { stage: [0.00, 0.42], vector: [0, 0, 1100], label: "Wing spoilers", ref: "o1.3.1.21,o1.3.1.22,o1.3.1.23,o1.3.1.24,o1.3.2.21,o1.3.2.22,o1.3.2.23,o1.3.2.24" },
  { stage: [0.08, 0.52], vector: [-1300, 0, 250], label: "Wing slats + tracks", ref: "o1.3.1.3,o1.3.1.4,o1.3.1.5,o1.3.1.6,o1.3.1.7,o1.3.1.8,o1.3.1.9,o1.3.1.10,o1.3.1.11,o1.3.1.12,o1.3.1.13,o1.3.1.14,o1.3.1.15,o1.3.2.3,o1.3.2.4,o1.3.2.5,o1.3.2.6,o1.3.2.7,o1.3.2.8,o1.3.2.9,o1.3.2.10,o1.3.2.11,o1.3.2.12,o1.3.2.13,o1.3.2.14,o1.3.2.15" },
  { stage: [0.14, 0.58], vector: [1500, 0, -450], label: "Wing flaps + track fairings", ref: "o1.3.1.16,o1.3.1.17,o1.3.1.18,o1.3.1.19,o1.3.1.20,o1.3.2.16,o1.3.2.17,o1.3.2.18,o1.3.2.19,o1.3.2.20" },
  { stage: [0.24, 0.66], vector: [0, 1500, 250], label: "Wingtip light housing (port)", ref: "o1.3.1.25,o1.3.1.26,o1.3.1.27" },
  { stage: [0.24, 0.66], vector: [0, -1500, 250], label: "Wingtip light housing (stbd)", ref: "o1.3.2.25,o1.3.2.26,o1.3.2.27" },
  { stage: [0.30, 0.72], vector: [200, 0, 1500], label: "Dorsal speed brake", ref: "o1.7.1,o1.7.2,o1.7.3,o1.7.4,o1.7.5,o1.7.6,o1.7.7,o1.7.8,o1.7.9,o1.7.10,o1.7.11,o1.7.12,o1.7.13,o1.7.14" },
  { stage: [0.38, 0.80], vector: [200, 1100, -1200], label: "Ventral speed brake (port)", ref: "o1.7.15,o1.7.16,o1.7.17,o1.7.18,o1.7.19,o1.7.20,o1.7.21,o1.7.22,o1.7.23,o1.7.24,o1.7.25,o1.7.26,o1.7.27,o1.7.28" },
  { stage: [0.38, 0.80], vector: [200, -1100, -1200], label: "Ventral speed brake (stbd)", ref: "o1.7.29,o1.7.30,o1.7.31,o1.7.32,o1.7.33,o1.7.34,o1.7.35,o1.7.36,o1.7.37,o1.7.38,o1.7.39,o1.7.40,o1.7.41,o1.7.42" },
  { stage: [0.48, 0.88], vector: [1600, 0, 0], label: "Beavertail access panels", ref: "o1.7.52,o1.7.53" },
  { stage: [0.56, 1.00], vector: [800, 0, -1400], label: "Tailhook + bay doors", ref: "o1.7.54,o1.7.55,o1.7.56,o1.7.57,o1.7.58,o1.7.59,o1.7.60,o1.7.61,o1.7.62,o1.7.63,o1.7.64,o1.7.65" }
];

const AIRFRAME = "o1.1";
// The skin reaches minimum opacity well before it finishes travelling, so the
// internals are readable while it is still clearing them.
const SKIN_FADE_WINDOW = [0, 0.45];
const SKIN_OPACITY = [1, 0.22];

function smoothstep(u) {
  const c = Math.min(1, Math.max(0, u));
  return c * c * (3 - 2 * c);
}

// A stage's own 0..1 progress, given the master ramp and the stage's window.
function windowed(ramp, from, to) {
  return to <= from ? (ramp >= to ? 1 : 0) : smoothstep((ramp - from) / (to - from));
}

// The whole staged separation at one point on the master ramp (0 = built,
// 1 = fully apart). Shared by both clips, which differ only in how they walk
// the ramp.
function explode(m, ramp) {
  for (const [ref, [stage, vector]] of Object.entries(SYSTEMS)) {
    const progress = windowed(ramp, stage[0] * ACT1_END, stage[1] * ACT1_END);
    if (progress > 0) {
      m.get(ref).translate(vector.map((c) => c * progress));
    }
  }
  for (const sub of SUBS) {
    const progress = windowed(
      ramp,
      ACT2_START + sub.stage[0] * ACT2_SPAN,
      ACT2_START + sub.stage[1] * ACT2_SPAN
    );
    if (progress > 0) {
      m.get(sub.ref).translate(sub.vector.map((c) => c * progress));
    }
  }
  const fade = windowed(ramp, SKIN_FADE_WINDOW[0], SKIN_FADE_WINDOW[1]);
  m.get(AIRFRAME).opacity(SKIN_OPACITY[0] + (SKIN_OPACITY[1] - SKIN_OPACITY[0]) * fade);
}

export const clips = {
  teardown: {
    label: "Staged teardown",
    // 60 s: a published frame of this 2,392-record assembly costs far more
    // than a display frame, so the clip is stretched to keep the per-frame
    // delta small at the paced-down playback rate.
    duration: 60,
    loop: true,
    update(t, m) {
      // Out and back on a sine, so the loop point is the built aircraft and
      // the reassembly is the teardown run backwards.
      explode(m, 0.5 - 0.5 * Math.cos(Math.PI * 2 * (t / 60)));
    }
  },

  explodedHold: {
    label: "Exploded hold",
    // The same staging, but it stops at full separation and sits there for a
    // third of the clip — the shape you want for a still review or a talk.
    duration: 24,
    loop: true,
    update(t, m) {
      const u = t / 24;
      let ramp;
      if (u < 0.33) {
        ramp = smoothstep(u / 0.33);
      } else if (u < 0.67) {
        ramp = 1;
      } else {
        ramp = 1 - smoothstep((u - 0.67) / 0.33);
      }
      explode(m, ramp);
    }
  }
};
