"""F-14D empennage: twin canted fins, rudders, all-moving stabilators, ventrals.

Everything here is built in the WATERLINE frame and lifted by ``stance()`` at the
end, like every other part module.

Two things decide whether a Tomcat tail reads correctly:

*   **The cant.**  ``G.FIN_CANT`` is the fin MID-PLANE angle, and the head-on
    view is unforgiving about it.  Both fins are generated by the same code with
    ``side`` multiplying every Y term, so the only difference between them is an
    exact IEEE sign flip -- there is no second code path that could drift.
*   **The root.**  A fin that lands on the nacelle crown as a butt joint kills
    the whole aft end.  The root is therefore built in two pieces: the fin loft
    is EXTRAPOLATED down through the skin (``FIN_BURY``) so it never shows a
    seam, and a lofted fairing rides the crown around it, sampled straight off
    ``SEC.surfaces`` so it stays glued to the skin when the body is retuned.
"""

from __future__ import annotations

import math

from cadgen import build123d as bd

from lib import geometry as G
from lib import palette as P
from lib import sections as SEC
from lib.airframe import stance
from lib.context import (biconvex_points, frame, group, mirror_pair,
                               naca4_points, section_frame)

M = G.M

# ---------------------------------------------------------------------------
# empennage constants that are NOT in geometry.py (shapes, not the envelope)
# ---------------------------------------------------------------------------

FIN_N = 40                      # aerofoil samples per half section
FIN_BURY = 0.300 * M            # how far the fin loft is extrapolated BELOW the
                                # root plane, so it exits the skin on a curve
X_FIN_TIP_TE = G.X_FIN_TIP_LE + G.FIN_TIP_CHORD

# rudder: aft 29 % of the local chord, hinge line straight in the fin plane
RUDDER_FRAC = 0.29
X_HINGE_ROOT = G.X_FIN_TE - RUDDER_FRAC * G.FIN_ROOT_CHORD
X_HINGE_TIP = X_FIN_TIP_TE - RUDDER_FRAC * G.FIN_TIP_CHORD
H_RUD_LO = 0.055 * G.FIN_HEIGHT
H_RUD_HI = 0.930 * G.FIN_HEIGHT
RUDDER_GAP = 16.0               # a real hinge gap, not a coincident face

# fin root fairing
X_FAIR_FWD = 14.060 * M
X_FAIR_AFT = SEC.X_SKIN_AFT
FAIR_R = 0.360 * M              # lateral reach of the fairing off the fin flank
FAIR_H = 0.235 * M              # its rise above the crown alongside the flank
FAIR_SINK = 0.120 * M           # how deep it is buried in the nacelle
FAIR_BURY = 0.026 * M           # outer edge sits UNDER the skin, never on it

# stabilator
STAB_A = math.radians(G.STAB_ANHEDRAL)
STAB_DROOP = 4.0                # deg trailing edge down.  A parked Tomcat with
                                # the hydraulics off droops its stabilators; it
                                # is the single most recognisable "cold jet"
                                # detail on the flight deck.
STAB_PIVOT_FRAC = 0.35          # pivot station as a fraction of the root chord
Z_STAB = -0.030 * M             # pivot height, just under the engine axis
STAB_THICK_TIP = 0.062 * M

# ventral fins
VENT_LE_ROOT = 16.200 * M
VENT_TE_ROOT = 17.380 * M
VENT_LE_SWEEP = 47.0
VENT_TE_SWEEP = 5.0
VENT_CANT = 16.0                # deg outward, top inboard
VENT_THICK_ROOT = 0.078 * M
VENT_THICK_TIP = 0.038 * M
VENT_BURY = 0.110 * M

GROOVE_W = 11.0                 # panel-line groove: 11 mm wide, 4.5 mm deep.
GROOVE_D = 4.5                  # A scribed line is sub-pixel at aircraft scale;
GROOVE_OUT = 30.0               # it reads because the edge overlay draws it.
FASTENER_R = 7.0
FASTENER_SINK = 4.6             # so 2.4 mm of dome stands proud


# ---------------------------------------------------------------------------
# small shared helpers
# ---------------------------------------------------------------------------


def _naca_half(t_frac, chord, xc):
    """Half-thickness of the symmetric NACA section used by ``naca4_points``.

    Same polynomial, evaluated at ONE station instead of sampled -- the fairing
    and the panel-line cutters have to know where the fin's flank is at an
    arbitrary chord fraction, and re-deriving it from the sampled point list
    would just be interpolation of the same curve.
    """
    if xc <= 0.0 or xc >= 1.0:
        return 0.0
    yt = 5 * t_frac * (0.2969 * math.sqrt(xc) - 0.1260 * xc - 0.3516 * xc ** 2
                       + 0.2843 * xc ** 3 - 0.1036 * xc ** 4)
    return chord * yt


def _split(pts, n):
    """Split a closed aerofoil point list into upper/lower runs, LE -> TE.

    Both runs share the LE and TE points exactly, so the two splines built from
    them close into a wire without a gap and keep the LE and TE as real corners
    instead of letting one periodic spline round them off.
    """
    upper = list(pts[:n])
    lower = [upper[0]] + list(reversed(pts[n:])) + [upper[-1]]
    return upper, lower


def _sec_face(plane, upper, lower):
    up = [plane.from_local_coords(bd.Vector(x, y, 0)) for x, y in upper]
    lo = [plane.from_local_coords(bd.Vector(x, y, 0)) for x, y in lower]
    return bd.Face(bd.Wire([bd.Spline(*up).edge(), bd.Spline(*lo).edge()]))


def _aerofoil_face(plane, pts, n):
    upper, lower = _split(pts, n)
    return _sec_face(plane, upper, lower)


def _rect_face(plane, x0, x1, y0, y1):
    pts = [plane.from_local_coords(bd.Vector(a, b, 0))
           for a, b in ((x0, y0), (x1, y0), (x1, y1), (x0, y1))]
    return bd.Face(bd.Wire(bd.Polyline(*pts, close=True).edges()))


def _skin_top(x, y):
    t, _ = SEC.surfaces(x, y)
    return t


def _skin_bot(x, y):
    _, b = SEC.surfaces(x, y)
    return b


def _skin_edge_y(x, z):
    """Outboard |y| where the skin passes through height z at station x.

    Bisection on ``SEC.surfaces`` rather than a local copy of the nacelle
    superellipse: the blended query is the authoritative "where is the skin",
    and the stabilator fairing has to sit on it, not on an approximation of it.
    """
    lo, hi = abs(G.Y_NACELLE), SEC.outer_half_width(x) + 2.0
    target = abs(z)
    for _ in range(44):
        mid = 0.5 * (lo + hi)
        top, bot = SEC.surfaces(x, mid)
        if top is None:
            hi = mid
            continue
        val = top if z >= 0.0 else -bot
        if val >= target:
            lo = mid
        else:
            hi = mid
    return lo


# ---------------------------------------------------------------------------
# fin frames and planform
# ---------------------------------------------------------------------------

FIN_C = math.radians(G.FIN_CANT)
FIN_SIN, FIN_COS, FIN_TAN = math.sin(FIN_C), math.cos(FIN_C), math.tan(FIN_C)


def _fin_le(t):
    return G.lerp(G.X_FIN_LE, G.X_FIN_TIP_LE, t)


def _fin_te(t):
    return G.lerp(G.X_FIN_TE, X_FIN_TIP_TE, t)


def _fin_chord(t):
    return _fin_te(t) - _fin_le(t)


def _fin_thick(t):
    return G.lerp(G.FIN_THICK_ROOT, G.FIN_THICK_TIP, t)


def _fin_hinge_x(t):
    return G.lerp(X_HINGE_ROOT, X_HINGE_TIP, t)


def _fin_plane(h, side):
    """Section frame perpendicular to the CANTED span axis.

    ``context.section_frame`` cannot serve a vertical surface: its normal is
    constrained to the horizontal plane, which is right for a stabilator and
    impossible for a fin.  ``context.frame`` is the same tool without that
    constraint -- explicit direction vectors, never ``Plane.rotated()``.  That
    is also what makes the cant exact: the span axis is
    ``(0, side*sin(cant), cos(cant))`` and the two fins differ only by the sign
    of ``side``, so their cants are identical to the last bit by construction.
    """
    t = h / G.FIN_HEIGHT
    origin = (_fin_le(t), side * (G.Y_FIN + h * FIN_TAN), G.FIN_ROOT_Z + h)
    return frame(origin, (1.0, 0.0, 0.0), (0.0, side * FIN_SIN, FIN_COS))


def _fin_world(x, h, yt, side):
    """World point at station ``x``, height ``h``, ``yt`` off the fin plane."""
    return bd.Vector(x,
                  side * (G.Y_FIN + h * FIN_TAN) + yt * FIN_COS,
                  G.FIN_ROOT_Z + h - yt * side * FIN_SIN)


def _fin_ht(x, h):
    """Fin half-thickness at station x and height h (0 off the planform)."""
    t = h / G.FIN_HEIGHT
    c = _fin_chord(t)
    return _naca_half(_fin_thick(t) / c, c, (x - _fin_le(t)) / c)


def _fin_heights(n=9):
    """Evenly spaced section heights, buried root to tip.

    EVEN spacing matters: chord, thickness and station all vary linearly in the
    span parameter, so a smooth loft through evenly spaced sections reproduces
    the straight-tapered fin exactly.  Uneven spacing would let the spline bow
    between stations and put a shallow S in the leading edge.
    """
    return [G.lerp(-FIN_BURY, G.FIN_HEIGHT, i / (n - 1)) for i in range(n)]


def _fin_loft(side):
    faces = []
    for h in _fin_heights():
        t = h / G.FIN_HEIGHT
        c = _fin_chord(t)
        pts = naca4_points(_fin_thick(t) / c, c, n=FIN_N)
        faces.append(_aerofoil_face(_fin_plane(h, side), pts, FIN_N))
    return bd.loft(faces)


def _hinge_prism(side, h_lo, h_hi, x_off, half_thk=0.6 * M):
    """Prism bounded forward by the straight rudder hinge plane."""
    x_aft = 20.6 * M
    corners = [(_fin_hinge_x(h_lo / G.FIN_HEIGHT) + x_off, h_lo),
               (_fin_hinge_x(h_hi / G.FIN_HEIGHT) + x_off, h_hi),
               (x_aft, h_hi),
               (x_aft, h_lo)]
    faces = []
    for yt in (-half_thk, half_thk):
        pts = [_fin_world(x, h, yt, side) for x, h in corners]
        faces.append(bd.Face(bd.Wire(bd.Polyline(*pts, close=True).edges())))
    return bd.loft(faces)


# ---------------------------------------------------------------------------
# thin surface slabs -- panel-line cutters and lit strips share one builder
# ---------------------------------------------------------------------------


def _chord_station_slab(sections, width, out, into, face_sign):
    """Slab following one face along a constant chord fraction.

    ``sections`` is [(plane, x_local, half_thickness), ...] in loft order.  With
    ``into``/``out`` set to a groove depth it is a panel-line cutter; with a
    couple of millimetres it is a lit strip that sits on the surface.
    """
    faces = []
    for plane, xc, ht in sections:
        y0 = face_sign * (ht - into)
        y1 = face_sign * (ht + out)
        faces.append(_rect_face(plane, xc - 0.5 * width, xc + 0.5 * width, y0, y1))
    return bd.loft(faces)


def _fin_chord_slab(side, f_chord, h0, h1, width, out, into, face_sign, n=5):
    secs = []
    for i in range(n):
        h = G.lerp(h0, h1, i / (n - 1))
        t = h / G.FIN_HEIGHT
        c = _fin_chord(t)
        ht = _naca_half(_fin_thick(t) / c, c, f_chord)
        secs.append((_fin_plane(h, side), f_chord * c, ht))
    return _chord_station_slab(secs, width, out, into, face_sign)


def _fin_rib_slab(side, h, f0, f1, width, out, into, face_sign, n=8):
    """Slab running CHORDWISE at a constant height, following the face.

    ``f0`` deliberately starts well aft of the nose: the tool's floor is
    piecewise linear between stations while the section's nose is not, and
    forward of about 10 % chord the straight chord loses the surface faster than
    the groove is deep, which breaks the panel line up into dashes.
    """
    t = h / G.FIN_HEIGHT
    c = _fin_chord(t)
    faces = []
    for i in range(n):
        f = G.lerp(f0, f1, i / (n - 1))
        x = _fin_le(t) + f * c
        ht = _naca_half(_fin_thick(t) / c, c, f)
        pl = frame(_fin_world(x, h, 0.0, side),
                   (0.0, FIN_COS, -side * FIN_SIN), (1.0, 0.0, 0.0))
        faces.append(_rect_face(pl, face_sign * (ht - into), face_sign * (ht + out),
                                -0.5 * width, 0.5 * width))
    return bd.loft(faces)


# ---------------------------------------------------------------------------
# fin, rudder, hinge fairings
# ---------------------------------------------------------------------------

SPARS = (0.095, 0.430)          # LE section joint and the main spar
RIBS = (0.185, 0.855)


def _fin(side):
    body = _fin_loft(side)
    body = body - [_hinge_prism(side, H_RUD_LO, H_RUD_HI, 0.0)]
    spar_tools = []
    for f in SPARS:
        for sgn in (1, -1):
            spar_tools.append(_fin_chord_slab(
                side, f, -0.02 * G.FIN_HEIGHT, 0.995 * G.FIN_HEIGHT,
                GROOVE_W, GROOVE_OUT, GROOVE_D, sgn))
    rib_tools = []
    for h_frac in RIBS:
        for sgn in (1, -1):
            rib_tools.append(_fin_rib_slab(
                side, h_frac * G.FIN_HEIGHT, 0.120, 0.695,
                GROOVE_W, GROOVE_OUT, GROOVE_D, sgn))
    # two batches: each is internally disjoint, but the ribs cross the spars
    body = body - spar_tools
    body = body - rib_tools
    return P.style(body, "fin", P.JOLLY_BLACK)


def _rudder(side):
    body = _fin_loft(side)
    keep = _hinge_prism(side, H_RUD_LO + RUDDER_GAP, H_RUD_HI - RUDDER_GAP,
                        RUDDER_GAP)
    body = body & keep
    return P.style(body, "rudder", P.JOLLY_BLACK)


def _hinge_fairings(side):
    """Three hinge fairings straddling the rudder gap on the fin trailing edge."""
    out = []
    for i, hf in enumerate((0.18, 0.50, 0.81)):
        h = G.lerp(H_RUD_LO, H_RUD_HI, hf)
        t = h / G.FIN_HEIGHT
        c = _fin_chord(t)
        x = _fin_hinge_x(t)
        ht = _naca_half(_fin_thick(t) / c, c, (x - _fin_le(t)) / c)
        pod = bd.scale(bd.Solid.make_sphere(1.0),
                    by=(0.135 * M, ht + 0.021 * M, 0.062 * M))
        pl = bd.Plane(origin=_fin_world(x + 0.020 * M, h, 0.0, side),
                   x_dir=bd.Vector(1.0, 0.0, 0.0),
                   z_dir=bd.Vector(0.0, side * FIN_SIN, FIN_COS))
        out.append(P.style(pl.location * pod, f"rudder_hinge_{i:02d}", P.JOLLY_BLACK))
    return group("rudder_hinges", out)


# ---------------------------------------------------------------------------
# fin root fairing -- a lofted skirt sampled off the real skin
# ---------------------------------------------------------------------------

FAIR_X = [14.060, 14.190, 14.320, 14.450, 14.580, 14.720, 14.880, 15.080,
          15.340, 15.680, 16.080, 16.520, 16.960, 17.360, 17.700, 17.980,
          18.170, 18.300]


def _fair_shape(x):
    """(rise, lateral reach, wall half-width) of the fairing at station x."""
    fade = G.smoothstep(X_FAIR_FWD, 14.760 * M, x)
    # the fairing must never stand taller than the fin's own leading edge at
    # that station, or it reads as a ridge poking out in front of the fin
    h_le = max(0.0, x - G.X_FIN_LE) / (G.X_FIN_TIP_LE - G.X_FIN_LE) * G.FIN_HEIGHT
    rise = min(FAIR_H * fade, 0.55 * h_le + 0.048 * M)
    u = rise / FAIR_H
    reach = G.lerp(0.075 * M, FAIR_R, u ** 0.6)
    wall = max(0.014 * M, _fin_ht(x, rise) - 0.017 * M)
    return rise, reach, wall, u


def _fair_offsets(d, rise, reach, wall, u):
    """Vertical offsets (top, bottom) from the skin at lateral distance d."""
    if d <= wall:
        delta = rise
        bury = 0.0
    else:
        s = G.clamp((wall + reach - d) / reach, 0.0, 1.0)
        delta = rise * (1.0 - math.sqrt(max(0.0, 1.0 - s * s)))
        bury = FAIR_BURY * (1.0 - s) ** 3
    sink_fwd = 0.042 * M * (1.0 - min(1.0, 2.2 * u))
    top = delta - bury - sink_fwd
    edge = -FAIR_BURY - sink_fwd
    d_max = wall + reach
    bot = G.lerp(-FAIR_SINK, edge, (d / d_max) ** 1.7)
    return top, bot


def _fair_ds(wall, reach):
    inner = [0.0, 0.45 * wall, 0.80 * wall]
    fillet = [wall + reach * (0.5 - 0.5 * math.cos(math.pi * i / 13))
              for i in range(14)]
    return inner + fillet


def _fin_fairing(side):
    faces = []
    for xm in FAIR_X:
        x = xm * M
        rise, reach, wall, u = _fair_shape(x)
        yc = side * (G.Y_FIN + 0.5 * rise * FIN_TAN)
        ds = _fair_ds(wall, reach)
        dys = [-d for d in reversed(ds[1:])] + ds
        top, bot = [], []
        for dy in dys:
            y = yc + dy
            z0 = _skin_top(x, y)
            if z0 is None:
                z0 = G.FIN_ROOT_Z
            dt, db = _fair_offsets(abs(dy), rise, reach, wall, u)
            top.append(bd.Vector(x, y, z0 + dt))
            bot.append(bd.Vector(x, y, z0 + db))
        faces.append(bd.Face(bd.Wire([bd.Spline(*top).edge(), bd.Spline(*bot).edge()])))
    return P.style(bd.loft(faces), "fin_root_fairing", P.JOLLY_BLACK)


# ---------------------------------------------------------------------------
# fin tip: RWR/ECM fairings, vent, anti-collision light, formation strip
# ---------------------------------------------------------------------------


def _tip_pod(side, x0, x1, half_w_fn, up_fn, dn_fn, n=13):
    """Streamlined pod lying along the fin tip, in the fin's own frame.

    ``up_fn``/``dn_fn`` give the pod's reach ABOVE and BELOW the tip plane
    separately, rather than a centre plus a radius: the pod has to keep swallowing
    the fin's tip edge all the way to its own nose, and a single centred ellipse
    lifts clear of it as soon as the section shrinks.
    """
    y_tip = side * (G.Y_FIN + G.FIN_HEIGHT * FIN_TAN)
    z_tip = G.FIN_ROOT_Z + G.FIN_HEIGHT
    secs = [bd.Vertex(*_fin_world(x0, G.FIN_HEIGHT, 0.0, side).to_tuple())]
    for i in range(1, n - 1):
        x = G.lerp(x0, x1, i / (n - 1))
        w, hu, hd = half_w_fn(x), up_fn(x), dn_fn(x)
        pl = frame((x, y_tip, z_tip),
                   (0.0, FIN_COS, -side * FIN_SIN), (1.0, 0.0, 0.0))
        up, lo = [], []
        for k in range(15):
            a = math.pi * k / 14
            up.append(pl.from_local_coords(
                bd.Vector(w * math.cos(a), hu * math.sin(a), 0)))
            lo.append(pl.from_local_coords(
                bd.Vector(w * math.cos(a), -hd * math.sin(a), 0)))
        secs.append(bd.Face(bd.Wire([bd.Spline(*up).edge(), bd.Spline(*lo).edge()])))
    secs.append(bd.Vertex(*_fin_world(x1, G.FIN_HEIGHT, 0.0, side).to_tuple()))
    return bd.loft(secs)


def _fin_tip(side):
    c_tip = G.FIN_TIP_CHORD
    x_le, x_te = G.X_FIN_TIP_LE, X_FIN_TIP_TE

    def fin_w(x):
        return _naca_half(G.FIN_THICK_TIP / c_tip, c_tip,
                          G.clamp((x - x_le) / c_tip, 0.0, 1.0))

    # main ECM/RWR cap: rides the whole tip chord, a little proud of the flanks
    x0, x1 = x_le - 0.055 * M, x_te + 0.115 * M
    xc = 0.5 * (x0 + x1)
    half = 0.5 * (x1 - x0)

    def prof(x):
        return max(0.02, (1.0 - ((x - xc) / half) ** 2)) ** 0.42

    cap = _tip_pod(side, x0, x1,
                   lambda x: (fin_w(x) + 0.014 * M) * prof(x) + 0.006 * M,
                   lambda x: 0.046 * M * prof(x) + 0.004 * M,
                   lambda x: 0.118 * M * (0.34 + 0.66 * prof(x)))
    kids = [P.style(cap, "fin_tip_ecm", P.JOLLY_GOLD)]

    # forward-looking RWR antenna in its own dielectric bullet
    xb0, xb1 = x_le - 0.235 * M, x_le + 0.215 * M
    xbc, hb = 0.5 * (xb0 + xb1), 0.5 * (xb1 - xb0)

    def bp(x):
        return max(0.02, 1.0 - ((x - xbc) / hb) ** 2) ** 0.40

    bullet = _tip_pod(side, xb0, xb1,
                      lambda x: 0.060 * M * bp(x),
                      lambda x: 0.036 * M * bp(x),
                      lambda x: 0.076 * M * bp(x), n=11)
    kids.append(P.style(bullet, "fin_tip_rwr_fwd", P.DIELECTRIC))

    # aft-looking RWR antenna over the rudder top
    xa0, xa1 = x_te - 0.205 * M, x_te + 0.170 * M
    xac, ha = 0.5 * (xa0 + xa1), 0.5 * (xa1 - xa0)

    def ap(x):
        return max(0.02, 1.0 - ((x - xac) / ha) ** 2) ** 0.42

    aft = _tip_pod(side, xa0, xa1,
                   lambda x: 0.052 * M * ap(x),
                   lambda x: 0.032 * M * ap(x),
                   lambda x: 0.070 * M * ap(x), n=11)
    kids.append(P.style(aft, "fin_tip_rwr_aft", P.DIELECTRIC))

    # fuel vent standing off the cap, and the anti-collision lens beside it
    vent_pl = bd.Plane(origin=_fin_world(x_te - 0.36 * M, G.FIN_HEIGHT + 0.052 * M,
                                      0.0, side),
                    x_dir=bd.Vector(1.0, 0.0, 0.0),
                    z_dir=bd.Vector(0.0, side * FIN_SIN, FIN_COS))
    vent = bd.scale(bd.Solid.make_sphere(1.0), by=(0.115 * M, 0.026 * M, 0.030 * M))
    kids.append(P.style(vent_pl.location * vent, "fin_vent", P.ALUM_DARK))

    lens_pl = bd.Plane(origin=_fin_world(x_le + 0.62 * M, G.FIN_HEIGHT + 0.036 * M,
                                      0.0, side),
                    x_dir=bd.Vector(1.0, 0.0, 0.0),
                    z_dir=bd.Vector(0.0, side * FIN_SIN, FIN_COS))
    lens = bd.scale(bd.Solid.make_sphere(1.0), by=(0.072 * M, 0.036 * M, 0.026 * M))
    kids.append(P.style(lens_pl.location * lens, "fin_light_white", P.LIGHT_WHITE))

    return group("fin_tip", kids)


def _formation_strip(side):
    """Electroluminescent strip on the OUTBOARD fin face.

    Outboard is ``side`` times the section frame's own thickness axis: for the
    starboard fin the frame's +y points inboard, so the sign has to follow.
    """
    strip = _fin_chord_slab(side, 0.615, 0.30 * G.FIN_HEIGHT, 0.80 * G.FIN_HEIGHT,
                            0.058 * M, 4.0, 2.5, side, n=4)
    return P.style(strip, "formation_strip", P.FORMATION)


def _fin_fasteners(side):
    """Fastener rows following the fin spars, as additive domes."""
    proto = bd.Solid.make_sphere(FASTENER_R)
    solids = []
    for f in SPARS:
        for sgn in (1, -1):
            h = 0.045 * G.FIN_HEIGHT
            while h < 0.965 * G.FIN_HEIGHT:
                t = h / G.FIN_HEIGHT
                c = _fin_chord(t)
                xc = (f * c) + 0.030 * M
                ht = _naca_half(_fin_thick(t) / c, c, xc / c)
                pl = _fin_plane(h, side)
                p = pl.from_local_coords(bd.Vector(xc, sgn * (ht - FASTENER_SINK), 0))
                solids.append(bd.Location(p) * proto)
                h += 0.115 * M
    # ONE leaf holding every dome.  Compound(obj=[...]) without children= is
    # exactly the collapse-to-one-occurrence behaviour wanted here: a fastener
    # row is one painted feature, not two hundred assembly parts, and two
    # hundred coloured leaves would swamp the render package.
    return P.style(bd.Compound(solids), "fin_fasteners", P.JOLLY_BLACK)


# ---------------------------------------------------------------------------
# stabilators -- one-piece all-moving slabs, drooped
# ---------------------------------------------------------------------------

Y_STAB_SIDE = _skin_edge_y(G.X_STAB_PIVOT, Z_STAB)
S_REF = (Y_STAB_SIDE - G.Y_STAB_PIVOT) / math.cos(STAB_A)
S_TIP = (0.5 * G.STAB_SPAN - G.Y_STAB_PIVOT) / math.cos(STAB_A)
S_IN = -0.200 * M
X_STAB_LE_REF = G.X_STAB_PIVOT - STAB_PIVOT_FRAC * G.STAB_ROOT_CHORD
STAB_TAN = math.tan(math.radians(G.STAB_LE_SWEEP))


def _stab_frac(s):
    return (s - S_REF) / (S_TIP - S_REF)


def _stab_chord(s):
    return G.lerp(G.STAB_ROOT_CHORD, G.STAB_TIP_CHORD, _stab_frac(s))


def _stab_thick(s):
    return G.lerp(G.STAB_THICK_ROOT, STAB_THICK_TIP, _stab_frac(s))


def _stab_le(s):
    return X_STAB_LE_REF + (s - S_REF) * math.cos(STAB_A) * STAB_TAN


def _droop(x, z):
    """Rigid rotation about the pivot axis: trailing edge DOWN.

    Applied to the section ORIGINS as well as to the frames, so the stabilator
    turns as one body instead of picking up a spanwise twist.
    """
    d = math.radians(STAB_DROOP)
    dx, dz = x - G.X_STAB_PIVOT, z - Z_STAB
    return (G.X_STAB_PIVOT + dx * math.cos(d) + dz * math.sin(d),
            Z_STAB - dx * math.sin(d) + dz * math.cos(d))


def _stab_plane(s, side, chord_shift=0.0):
    y = side * (G.Y_STAB_PIVOT + s * math.cos(STAB_A))
    z = Z_STAB - s * math.sin(STAB_A)
    x, zr = _droop(_stab_le(s) + chord_shift, z)
    return section_frame((x, y, zr), 0.0, STAB_DROOP, side)


STAB_N = 34

# Span stations, root to tip.  The GAP RATIO between neighbours is what matters,
# not the count: OCC's ThruSections fits a spline across the sections, and a
# 623 mm step followed by a 16 mm one made it overshoot to a 6 m^3 balloon that
# reached 2 m off the aircraft.  These gaps never change by more than 2x, which
# resolves the rounded tip without letting the spline ring.
STAB_STATIONS = [-200.0, 380.0, 950.0, 1500.0, 2020.0, 2500.0, 2900.0, 3200.0,
                 3390.0, 3490.0, 3545.0, 3572.0, 3584.0, None]
STAB_TIP_ROUND = 190.0          # length of the elliptical tip closure


def _stab_tip_shape(s):
    """(thickness scale, chord scale) closing the tip as a rounded edge."""
    d = S_TIP - s
    if d >= STAB_TIP_ROUND:
        return 1.0, 1.0
    q = (STAB_TIP_ROUND - d) / STAB_TIP_ROUND
    return math.sqrt(max(0.0, 1.0 - (0.975 * q) ** 2)), 1.0 - 0.05 * q ** 1.7


def _stab_sections(side):
    faces = []
    for s in STAB_STATIONS:
        s = S_TIP if s is None else s
        k_t, k_c = _stab_tip_shape(s)
        c0 = _stab_chord(s)
        c = c0 * k_c
        pts = biconvex_points(_stab_thick(s) * k_t / c, c, n=STAB_N, le_round=0.10)
        faces.append(_aerofoil_face(
            _stab_plane(s, side, chord_shift=c0 * (1.0 - k_c) * 0.55), pts, STAB_N))
    return faces


def _stab_ht(s, f):
    """Half-thickness of the biconvex section at chord fraction f."""
    c = _stab_chord(s)
    tf = _stab_thick(s) / c
    return c * tf * 0.5 * math.sin(math.pi * f ** 0.90)


def _stabilator(side):
    body = bd.loft(_stab_sections(side))
    tools = []
    for f in (0.135, 0.640):
        secs = []
        for i in range(5):
            s = G.lerp(0.10 * M, S_TIP - 0.10 * M, i / 4)
            secs.append((_stab_plane(s, side), f * _stab_chord(s), _stab_ht(s, f)))
        for sgn in (1, -1):
            tools.append(_chord_station_slab(secs, GROOVE_W, GROOVE_OUT,
                                             GROOVE_D, sgn))
    body = body - tools
    return P.style(body, "stabilator", P.GREY_DARK)


def _stab_fairing(side):
    """Teardrop pivot fairing where the stabilator leaves the nacelle side."""
    x0, x1, xp = 14.900 * M, 17.420 * M, 15.820 * M
    b0, c0 = 0.268 * M, 0.252 * M

    def prof(x):
        if x <= xp:
            u = (xp - x) / (xp - x0)
            return max(0.0, 1.0 - u * u) ** 0.62
        u = (x - xp) / (x1 - xp)
        return max(0.0, 1.0 - u ** 2.4) ** 0.62

    secs = []
    n = 15
    for i in range(n):
        x = G.lerp(x0, x1, i / (n - 1))
        yc = side * (_skin_edge_y(x, Z_STAB) - 0.62 * b0)
        if i in (0, n - 1):
            secs.append(bd.Vertex(x, yc, Z_STAB))
            continue
        f = prof(x)
        b, c = b0 * f, c0 * f
        up, lo = [], []
        for k in range(17):
            a = math.pi * k / 16
            up.append(bd.Vector(x, yc + side * b * math.cos(a), Z_STAB + c * math.sin(a)))
            lo.append(bd.Vector(x, yc + side * b * math.cos(a), Z_STAB - c * math.sin(a)))
        secs.append(bd.Face(bd.Wire([bd.Spline(*up).edge(), bd.Spline(*lo).edge()])))
    return P.style(bd.loft(secs), "stab_pivot_fairing", P.GREY_DARK)


# ---------------------------------------------------------------------------
# ventral fins
# ---------------------------------------------------------------------------

VENT_C = math.radians(VENT_CANT)
VENT_SIN, VENT_COS, VENT_TAN = math.sin(VENT_C), math.cos(VENT_C), math.tan(VENT_C)
Z_VENT_REF = _skin_bot(0.5 * (VENT_LE_ROOT + VENT_TE_ROOT), G.Y_VENTRAL)
VENT_N = 30


def _vent_le(h):
    return VENT_LE_ROOT + h * math.tan(math.radians(VENT_LE_SWEEP))


def _vent_te(h):
    return VENT_TE_ROOT + h * math.tan(math.radians(VENT_TE_SWEEP))


def _vent_plane(h, side):
    origin = (_vent_le(h), side * (G.Y_VENTRAL + h * VENT_TAN), Z_VENT_REF - h)
    return frame(origin, (1.0, 0.0, 0.0), (0.0, side * VENT_SIN, -VENT_COS))


VENT_STATIONS = [-VENT_BURY, -20.0, 70.0, 165.0, 260.0, 350.0, 425.0, 470.0,
                 498.0, 512.0, G.VENTRAL_HEIGHT]
VENT_TIP_ROUND = 62.0


def _ventral(side):
    faces = []
    for h in VENT_STATIONS:
        c = _vent_te(h) - _vent_le(h)
        t = G.clamp(h / G.VENTRAL_HEIGHT, 0.0, 1.0)
        thk = G.lerp(VENT_THICK_ROOT, VENT_THICK_TIP, t)
        d = G.VENTRAL_HEIGHT - h
        if d < VENT_TIP_ROUND:
            q = (VENT_TIP_ROUND - d) / VENT_TIP_ROUND
            thk *= math.sqrt(max(0.0, 1.0 - (0.975 * q) ** 2))
        pts = biconvex_points(thk / c, c, n=VENT_N, le_round=0.04)
        faces.append(_aerofoil_face(_vent_plane(h, side), pts, VENT_N))
    return P.style(bd.loft(faces), "ventral_fin", P.JOLLY_BLACK)


def _ventral_fairing(side):
    """Small skirt where the ventral root meets the nacelle underside."""
    xs = [15.960, 16.100, 16.240, 16.420, 16.640, 16.880, 17.120, 17.320,
          17.460, 17.580]
    reach, rise, sink = 0.130 * M, 0.062 * M, 0.075 * M
    faces = []
    for xm in xs:
        x = xm * M
        fade = (G.smoothstep(15.960 * M, 16.320 * M, x)
                * (1.0 - G.smoothstep(17.320 * M, 17.580 * M, x)))
        r = G.lerp(0.030 * M, reach, fade)
        ri = rise * fade
        wall = max(0.010 * M, 0.5 * G.lerp(VENT_THICK_ROOT, VENT_THICK_TIP, 0.0)
                   * math.sin(math.pi * G.clamp((x - VENT_LE_ROOT)
                                                / (VENT_TE_ROOT - VENT_LE_ROOT),
                                                0.02, 0.98) ** 0.9) - 0.008 * M)
        ds = [0.0, 0.5 * wall] + [wall + r * (0.5 - 0.5 * math.cos(math.pi * i / 9))
                                  for i in range(10)]
        dys = [-d for d in reversed(ds[1:])] + ds
        d_max = wall + r
        top, bot = [], []
        for dy in dys:
            y = side * G.Y_VENTRAL + dy
            z0 = _skin_bot(x, y)
            if z0 is None:
                z0 = Z_VENT_REF
            d = abs(dy)
            if d <= wall:
                delta = ri
            else:
                s = G.clamp((wall + r - d) / r, 0.0, 1.0)
                delta = ri * (1.0 - math.sqrt(max(0.0, 1.0 - s * s)))
            edge = 0.014 * M + 0.040 * M * (1.0 - fade)
            lower = -delta + edge * (1.0 - G.clamp((d_max - d) / max(r, 1.0), 0.0, 1.0))
            top.append(bd.Vector(x, y, z0 + sink))
            bot.append(bd.Vector(x, y, z0 + lower))
        # collapse the two curves onto each other at the outer edge
        bot[0] = bd.Vector(bot[0].X, bot[0].Y, top[0].Z)
        bot[-1] = bd.Vector(bot[-1].X, bot[-1].Y, top[-1].Z)
        faces.append(bd.Face(bd.Wire([bd.Spline(*top).edge(), bd.Spline(*bot).edge()])))
    return P.style(bd.loft(faces), "ventral_fairing", P.JOLLY_BLACK)


# ---------------------------------------------------------------------------


def build():
    kids = []
    kids += mirror_pair(_fin, "fin")
    kids += mirror_pair(_fin_fairing, "fin_root_fairing")
    kids += mirror_pair(_rudder, "rudder")
    kids += mirror_pair(_hinge_fairings, "rudder_hinges")
    kids += mirror_pair(_fin_tip, "fin_tip")
    kids += mirror_pair(_formation_strip, "formation_strip")
    kids += mirror_pair(_fin_fasteners, "fin_fasteners")
    kids += mirror_pair(_stabilator, "stabilator")
    kids += mirror_pair(_stab_fairing, "stab_pivot_fairing")
    kids += mirror_pair(_ventral, "ventral_fin")
    kids += mirror_pair(_ventral_fairing, "ventral_fairing")
    return stance(group("empennage", kids))


if __name__ == "__main__":
    import time

    t0 = time.time()
    shape = build()
    print(f"empennage {time.time() - t0:.1f}s")
    bb = shape.bounding_box()
    print(f"bbox x {bb.min.X / M:7.3f}..{bb.max.X / M:7.3f}  "
          f"y {bb.min.Y / M:7.3f}..{bb.max.Y / M:7.3f}  "
          f"z {bb.min.Z / M:7.3f}..{bb.max.Z / M:7.3f}")
