"""F-14D Super Tomcat -- master geometry.

THE SINGLE SOURCE OF TRUTH.  Every part module imports this and QUERIES it.
Never hard-code a coordinate that this module can answer; if a part touches the
airframe, place it against a function here so it stays attached when the surface
is tuned.

Frame
-----
    +X  aft   (nose at X=0, tail at X=LENGTH)
    +Y  left  (port)
    +Z  up
    Z=0 is the ground plane; the aircraft sits on its gear.

Units are MILLIMETRES (repo default).  Real-world metres are converted once,
here, so the rest of the model reads in mm like every other repo part.

Dimensions and their source
---------------------------
Length 62 ft 8.5 in (19.11 m), span 64 ft 1.5 in (19.55 m) at 20 deg, 38 ft
2.5 in (11.65 m) at 68 deg, height 16 ft (4.88 m), wing area 565 sq ft --
Heatblur F-14 NATOPS-derived manual and flugzeuginfo.net, cross-checked against
the Smithsonian NASM F-14D(R) record.  Planform stations, glove sweep, inlet
wall offsets, fin cant and the section evolution were measured off the F-14D
general-arrangement drawing (Wikimedia Commons ``File:F-14D.jpg``, 3028x4863)
by thresholding the ink and reading the silhouette column by column; that
extraction put the swept span within 0.8 % of the published figure, which is
what sets the confidence on the derived numbers.

The blended body
----------------
The Tomcat is ONE continuous lifting body, not a fuselage with nacelles bolted
on.  So the airframe skin is a single multi-section loft: at every station a
full-width closed section is generated by SMOOTHLY BLENDING the component
volumes that exist there -- forebody, gloves, nacelles, the flat pancake tunnel,
the dorsal spine.  Blending happens in the section maths (:func:`smax` /
:func:`smin`), which means the glove-to-fuselage and nacelle-to-pancake
transitions are continuous BY CONSTRUCTION.  There is no fillet anywhere in the
primary surface, and there is nothing to "join".
"""

from __future__ import annotations

import math

# ---------------------------------------------------------------------------
# overall envelope
# ---------------------------------------------------------------------------

M = 1000.0                     # metres -> millimetres

LENGTH = 19.110 * M            # nose tip to the aft end of the nozzles
SPAN_20 = 19.545 * M           # wings at 20 deg (the commanded state)
SPAN_68 = 11.646 * M           # wings at 68 deg
SPAN_75 = 10.150 * M           # oversweep, for reference only
HEIGHT = 4.880 * M             # ground to fin tip, gear down
WING_AREA = 52.49 * M * M      # 565 sq ft reference area

SWEEP = 20.0                   # commanded wing sweep for this build, degrees

# Ground stance.  The aircraft sits nose-slightly-down on its oleos; these are
# the numbers the gear modules must hit and the body loft is lifted to match.
# The waterline is the ENGINE AXIS.  Fixing it there means the nacelle, nozzle
# and fin numbers measured off the rear view drop straight in.
#
# Its height is solved, not chosen, and the first solve was WRONG: 1.780 m comes
# from putting the fin tip (3.10 m above the axis) at the published 4.88 m
# overall height for a LEVEL aircraft.  But the published height is the parked
# height, which already includes whatever rake the aircraft sits at -- so adding
# GROUND_PITCH on top double-counted it and made the model 5.16 m tall, 5.8 %
# over spec, because pitching nose-down about the origin lifts the whole tail.
# Re-solved with the rake included.  It also lands the ventral fin tips ~0.43 m
# off the deck, which is the clearance the real aircraft has -- an independent
# check that did not go into the solve.
#
# Both gear modules derive the ground plane from these two constants rather than
# hard-coding a leg length, so they follow this automatically.
GROUND_Z = 0.0
WATERLINE = 1.496 * M
GROUND_PITCH = -0.6            # degrees, nose down at rest (oleo compression)

# ---------------------------------------------------------------------------
# longitudinal stations (mm aft of the nose tip)
# ---------------------------------------------------------------------------

X_NOSE = 0.0
X_RADOME_AFT = 2.480 * M       # radome/bulkhead joint ring
X_TCS_POD = 1.760 * M          # chin pod centres
X_WINDSCREEN = 3.870 * M       # windscreen base
X_CANOPY_FWD = 4.290 * M       # canopy front arch
X_CANOPY_APEX = 5.960 * M      # highest point of the canopy
X_CANOPY_AFT = 7.190 * M       # canopy aft arch / turtledeck start
X_GLOVE_LE_ROOT = 2.140 * M    # glove LE line's CENTRELINE INTERCEPT (a
                               # construction point; the glove starts at the
                               # inlet -- see glove_outer_y)
X_INLET_LIP = 6.290 * M        # inlet cowl front face
X_INLET_THROAT = 7.900 * M
X_PIVOT = 9.630 * M            # wing pivot centre station
X_PANCAKE_FWD = 8.900 * M      # flat tunnel starts
X_PANCAKE_AFT = 16.150 * M     # flat tunnel ends at the beavertail
X_FIN_LE = 14.550 * M          # fin leading edge root
X_FIN_TE = 18.300 * M          # fin trailing edge root
X_STAB_PIVOT = 15.980 * M      # stabilator pivot station
X_SPEEDBRAKE_FWD = 13.900 * M
X_SPEEDBRAKE_AFT = 15.600 * M
X_NOZZLE_START = 17.250 * M    # convergent section begins
X_TAIL = LENGTH
X_BEAVER_TIP = 18.360 * M      # beavertail trailing point on the centreline

# gear stations
X_NOSE_GEAR = 3.120 * M
X_MAIN_GEAR = 10.640 * M

# ---------------------------------------------------------------------------
# lateral stations (mm from the centreline; +Y is port)
# ---------------------------------------------------------------------------

# THE NUMBER THAT DECIDES WHETHER THE PLANFORM READS AS A TOMCAT.
# The nacelle axes are NOT close together.  Measured from the GA drawing's rear
# view by clustering the two solid nozzle-centre discs: y = +1.461 and -1.453 m,
# which agree to 8 mm and put the axes 2.92 m apart.  An earlier estimate of
# 1.19 m -- which "looked right" -- would have made the aircraft 22 % too narrow
# across the nacelles, the single most common way a Tomcat model goes wrong.
Y_NACELLE = 1.457 * M          # nacelle/engine axis at the nozzle
Y_NACELLE_INLET = 1.330 * M    # nacelle axis at the inlet; the nacelles splay
                               # outward ~0.6 deg going aft
Y_INLET_OUTER = 1.706 * M      # inlet outer cowl wall
Y_INLET_INNER = 0.950 * M      # inlet inner cowl wall
Y_SPLITTER = 0.820 * M         # fuselage side: the 130 mm boundary-layer gap
                               # between it and the inner cowl is the F-14's
                               # most recognisable inlet feature
Y_PIVOT = 1.320 * M            # wing pivot centre
Y_GLOVE_OUTER = 2.240 * M      # fixed glove outer edge == the wing/glove seal
Y_WING_ROOT = Y_GLOVE_OUTER    # the moving panel starts where the glove ends
Y_FIN = 1.490 * M              # fin root mid-plane, just outboard of the
                               # nacelle axis (measured, rear view)
Y_VENTRAL = 1.310 * M          # ventral fin root
Y_MAIN_GEAR = 1.005 * M        # main wheel centre track/2 (2.01 m track)
Y_STAB_PIVOT = 1.400 * M       # stabilator pivot

# ---------------------------------------------------------------------------
# wing (variable sweep)
# ---------------------------------------------------------------------------

# Pivot radius and tip offset are SOLVED, not guessed: they are the unique pair
# that reproduces both published spans (19.545 m at 20 deg, 11.646 m at 68 deg)
# for a pivot at Y_PIVOT.  The solution independently predicts the swept tip at
# station 16.95 m, and the GA drawing measures 16.99 m -- which is what confirms
# X_PIVOT.  The 75 deg oversweep span does NOT fit this pair, because past ~70
# deg the widest point moves from the tip leading corner to the trailing corner.
WING_PIVOT_R = 8.5936 * M      # pivot to wingtip
WING_TIP_PHI = -9.6            # deg: pivot->tip line offset from the LE sweep
WING_ROOT_CHORD = 4.490 * M    # exposed root chord at the glove seal
WING_TIP_CHORD = 1.290 * M
WING_THICK_ROOT = 0.310 * M    # NACA 64A209 mod at the root
WING_THICK_TIP = 0.110 * M
WING_DIHEDRAL = 0.0            # the wing itself is flat; the glove carries it
GLOVE_LE_SWEEP = 69.2          # deg, fixed glove leading edge (fitted to the
                               # drawing silhouette from x=6.78 to 9.10 m: the
                               # edge is straight to within a pixel over 2.3 m)

# slats / flaps as fractions of local chord
SLAT_CHORD_FRAC = 0.17
FLAP_CHORD_FRAC = 0.28
SPOILER_CHORD_FRAC = 0.16

# ---------------------------------------------------------------------------
# empennage
# ---------------------------------------------------------------------------

# Cant measured two independent ways off the rear view: the fin's INNER surface
# leans out 7.4 deg and its OUTER surface 2.6 deg, because the fin thins toward
# the tip.  The mid-plane -- the actual cant -- is the mean of the two.
FIN_CANT = 5.0                 # deg outboard, top away from the centreline
FIN_ROOT_Z = 0.750 * M         # fin root above the waterline (on the nacelle)
FIN_HEIGHT = 2.350 * M         # root chord plane to tip
FIN_ROOT_CHORD = 3.750 * M
FIN_TIP_CHORD = 1.800 * M
FIN_LE_SWEEP = 46.8            # deg (falls out of the root/tip LE stations)
FIN_THICK_ROOT = 0.250 * M
FIN_THICK_TIP = 0.090 * M
X_FIN_TIP_LE = 17.050 * M

STAB_SPAN = 9.970 * M          # tip to tip, both stabilators
STAB_ROOT_CHORD = 2.640 * M
STAB_TIP_CHORD = 0.780 * M
STAB_LE_SWEEP = 50.5           # deg
STAB_ANHEDRAL = 3.0            # deg down
STAB_THICK_ROOT = 0.185 * M

VENTRAL_HEIGHT = 0.520 * M
VENTRAL_CHORD = 1.180 * M

# ---------------------------------------------------------------------------
# propulsion
# ---------------------------------------------------------------------------

INLET_WIDTH = 0.870 * M        # capture width of one rectangular inlet
INLET_HEIGHT = 1.150 * M       # capture height at the lip
INLET_RAKE = 15.0              # deg, lip rake in side view
DUCT_RADIUS = 0.545 * M        # circular duct at the engine face
NOZZLE_R_MAX = 0.640 * M       # widest point of the nozzle shroud
NOZZLE_R_EXIT = 0.560 * M      # exit plane radius, mil power (petals part-open)
NOZZLE_PETALS = 18             # F110-GE-400 external petal count
NOZZLE_LEN = 1.860 * M

# ---------------------------------------------------------------------------
# landing gear
# ---------------------------------------------------------------------------

NOSE_TIRE_D = 0.560 * M
NOSE_TIRE_W = 0.170 * M
MAIN_TIRE_D = 0.940 * M
MAIN_TIRE_W = 0.300 * M
NOSE_TRACK = 0.470 * M         # between the twin nose wheels
MAIN_TRACK = 2.010 * M
WHEELBASE = X_MAIN_GEAR - X_NOSE_GEAR

# ---------------------------------------------------------------------------
# smooth blending -- the heart of the "everything blends" requirement
# ---------------------------------------------------------------------------


def smax(a, b, k):
    """Smooth maximum with COMPACT support.  ``k`` is the blend width in mm.

    Cubic polynomial with compact support, NOT softplus/log-sum-exp.  Softplus
    is C-inf but its curvature is unbounded as k shrinks and it perturbs the
    surface everywhere; the blend where the inlet bridge met the forebody flank
    came out as a near-corner that no amount of extra sampling could resolve --
    97 samples per section were no better than 53, because the corner is in the
    function, not the sampling.

    The cube matters.  The obvious quadratic blend (``h*(1-h)``) is only C1, so
    curvature JUMPS at the edge of the blend band -- and a curvature jump on a
    specular surface draws a visible line, which put a crease down the full
    length of the aft fuselage at every feature rail.  ``h**3`` has zero first
    AND second derivative where the blend meets plain max(), so the transition
    is invisible.  Exactly max() outside |a-b| < k; adds at most k/6.
    """
    if k <= 1e-9:
        return max(a, b)
    h = max(k - abs(a - b), 0.0) / k
    return max(a, b) + h * h * h * k / 6.0


def smin(a, b, k):
    return -smax(-a, -b, k)


def smax_all(values, k):
    it = iter(values)
    out = next(it)
    for v in it:
        out = smax(out, v, k)
    return out


def smin_all(values, k):
    it = iter(values)
    out = next(it)
    for v in it:
        out = smin(out, v, k)
    return out


def clamp(v, lo, hi):
    return lo if v < lo else hi if v > hi else v


def smoothstep(edge0, edge1, x):
    if edge1 == edge0:
        return 0.0 if x < edge0 else 1.0
    t = clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def lerp(a, b, t):
    return a + (b - a) * t


def _smooth(pts, passes=2):
    """Light smoothing of a MEASURED control curve, endpoints pinned.

    The station data was read off a scanned drawing, so it carries about a
    pixel of noise -- roughly +-8 mm at this scale.  A monotone interpolant
    reproduces that noise faithfully, and a loft through it puts a visible
    ripple down the fuselage.  Two passes of a [1,2,1] kernel remove the
    measurement noise while leaving the shape, which is metres, untouched.
    """
    out = [(x, v) for x, v in pts]
    for _ in range(passes):
        new = [out[0]]
        for i in range(1, len(out) - 1):
            v = 0.25 * out[i - 1][1] + 0.5 * out[i][1] + 0.25 * out[i + 1][1]
            new.append((out[i][0], v))
        new.append(out[-1])
        out = new
    return out


_SLOPE_CACHE = {}


def _slopes(pts):
    """Fritsch-Carlson (PCHIP) tangents for a control curve.

    NOT smoothstep between knots.  Smoothstep has ZERO derivative at BOTH ends
    of every interval, so a curve built from it is flat at each control point
    and steep between them -- a staircase.  Lofting through such curves put a
    visible ripple down the whole fuselage: every knot became a crease.  PCHIP
    is C1 with sensible tangents and cannot overshoot, so control points stay
    control points instead of becoming features.
    """
    key = id(pts)
    hit = _SLOPE_CACHE.get(key)
    if hit is not None and hit[0] is pts:
        return hit[1]
    n = len(pts)
    if n < 2:
        return [0.0] * n
    h = [pts[i + 1][0] - pts[i][0] for i in range(n - 1)]
    delta = [(pts[i + 1][1] - pts[i][1]) / h[i] if h[i] else 0.0 for i in range(n - 1)]
    m = [0.0] * n
    m[0] = delta[0]
    m[-1] = delta[-1]
    for i in range(1, n - 1):
        if delta[i - 1] * delta[i] <= 0.0:
            m[i] = 0.0                       # local extremum: flat, no overshoot
        else:
            w1 = 2.0 * h[i] + h[i - 1]
            w2 = h[i] + 2.0 * h[i - 1]
            m[i] = (w1 + w2) / (w1 / delta[i - 1] + w2 / delta[i])
    _SLOPE_CACHE[key] = (pts, m)
    return m


def _curve(pts, x):
    """Monotone piecewise-cubic through (x, value) control points."""
    if x <= pts[0][0]:
        return pts[0][1]
    if x >= pts[-1][0]:
        return pts[-1][1]
    m = _slopes(pts)
    lo, hi = 0, len(pts) - 1
    while hi - lo > 1:                         # binary search the interval
        mid = (lo + hi) // 2
        if pts[mid][0] <= x:
            lo = mid
        else:
            hi = mid
    x0, v0 = pts[lo]
    x1, v1 = pts[lo + 1]
    h = x1 - x0
    t = (x - x0) / h
    t2, t3 = t * t, t * t * t
    return (v0 * (2 * t3 - 3 * t2 + 1) + m[lo] * h * (t3 - 2 * t2 + t)
            + v1 * (-2 * t3 + 3 * t2) + m[lo + 1] * h * (t3 - t2))


# ---------------------------------------------------------------------------
# component surfaces.  Each returns (present, top_z, bottom_z, half_width) for
# a station; the section builder blends them.
# ---------------------------------------------------------------------------

# Forebody half-width.  Forward of the inlet these are the MEASURED silhouette
# half-widths and the lobe closes on them.  Aft of the inlet the curve is
# deliberately widened past the real fuselage side so the lobe OVERLAPS the
# nacelles instead of closing between them: a lobe that closes there ends on a
# vertical tangent with the inlet shelf 0.23 m below it, and that 50 mm-wide
# cliff was the single worst curvature spike in the whole section set -- worse
# than anything the blend could round off, and immune to extra sampling. The
# real fuselage side and the boundary-layer slot are CUT back in afterwards,
# which is where they get their crisp machined walls anyway.
FOREBODY_HALF_W = [
    (0.000 * M, 0.010 * M), (0.410 * M, 0.137 * M), (0.830 * M, 0.315 * M),
    (1.240 * M, 0.422 * M), (1.660 * M, 0.509 * M), (2.070 * M, 0.588 * M),
    (2.480 * M, 0.648 * M), (2.900 * M, 0.749 * M), (3.310 * M, 0.756 * M),
    (3.930 * M, 0.766 * M), (4.550 * M, 0.791 * M), (5.170 * M, 0.807 * M),
    (5.800 * M, 0.812 * M), (6.290 * M, 0.818 * M), (7.000 * M, 0.960 * M),
    (7.600 * M, 1.115 * M), (8.400 * M, 1.270 * M), (9.400 * M, 1.375 * M),
    (10.500 * M, 1.430 * M), (13.000 * M, 1.460 * M), (16.150 * M, 1.460 * M),
]
FOREBODY_HALF_W = _smooth(FOREBODY_HALF_W, 2)

# ---------------------------------------------------------------------------
# canopy / spine lobe -- a SEPARATE narrow component riding on the deck.
#
# It has to be separate.  Folded into the forebody lobe, one half-width has to
# serve both the fuselage (1.4 m aft) and the canopy (0.5 m), so the canopy
# comes out as wide as the fuselage or the fuselage as narrow as the canopy.
# As its own lobe the bubble sits ON the deck and blends into the turtledeck,
# which is exactly what it does on the aircraft.
# ---------------------------------------------------------------------------

CANOPY_HALF_W = [
    (3.700 * M, 0.180 * M), (3.870 * M, 0.330 * M), (4.290 * M, 0.452 * M),
    (4.800 * M, 0.500 * M), (5.400 * M, 0.512 * M), (5.960 * M, 0.505 * M),
    (6.500 * M, 0.470 * M), (7.000 * M, 0.420 * M), (7.600 * M, 0.360 * M),
    (9.000 * M, 0.320 * M), (11.000 * M, 0.290 * M), (13.400 * M, 0.240 * M),
    (14.200 * M, 0.150 * M),
]

CANOPY_TOP = [
    (3.700 * M, 0.905 * M), (3.870 * M, 1.020 * M), (4.290 * M, 1.290 * M),
    (4.800 * M, 1.545 * M), (5.400 * M, 1.672 * M), (5.960 * M, 1.701 * M),
    (6.500 * M, 1.652 * M), (7.000 * M, 1.520 * M), (7.600 * M, 1.310 * M),
    (9.000 * M, 1.075 * M), (11.000 * M, 0.910 * M), (13.400 * M, 0.790 * M),
    (14.200 * M, 0.720 * M),
]

# Crown line, ABSOLUTE height above the waterline (= engine axis), read off the
# GA side view.  Through the cockpit this follows the CANOPY OUTER LINE, not the
# sill: the body is lofted to the canopy's own surface and the cockpit opening
# is cut out of it afterwards, so the transparency sits exactly on the surface
# it came from and the canopy-to-spine fairing is continuous by construction
# rather than being a gap that has to be fudged shut.
# Aft of ~9.4 m the drawing's top edge is the SWEPT WING lying over the
# fuselage, not the spine, so those stations are the turtledeck fitted through
# the uncontaminated ends rather than the raw trace.
FOREBODY_TOP = [
    (0.000 * M, -0.100 * M), (0.500 * M, 0.003 * M), (1.000 * M, 0.260 * M),
    (1.500 * M, 0.459 * M), (2.000 * M, 0.608 * M), (2.480 * M, 0.712 * M),
    (3.000 * M, 0.812 * M), (3.480 * M, 0.882 * M), (3.970 * M, 0.940 * M),
    (4.470 * M, 0.985 * M), (4.970 * M, 1.018 * M), (5.460 * M, 1.038 * M),
    (5.960 * M, 1.046 * M), (6.460 * M, 1.040 * M), (6.950 * M, 1.020 * M),
    (7.450 * M, 0.985 * M), (7.950 * M, 0.940 * M), (8.440 * M, 0.895 * M),
    (8.940 * M, 0.855 * M), (9.440 * M, 0.818 * M), (10.430 * M, 0.768 * M),
    (11.430 * M, 0.735 * M), (12.420 * M, 0.712 * M), (13.410 * M, 0.698 * M),
    (14.410 * M, 0.688 * M), (16.150 * M, 0.668 * M),
]
FOREBODY_TOP = _smooth(FOREBODY_TOP, 2)

# Keel line, ABSOLUTE height above the waterline (negative = below the engine
# axis).  The chin-pod and nose-gear-door stations in the raw trace are dropped;
# they are separate bodies hanging under the keel, not the keel itself.
FOREBODY_BOT = [
    (0.000 * M, -0.155 * M), (0.500 * M, -0.204 * M), (1.000 * M, -0.361 * M),
    (1.500 * M, -0.444 * M), (2.000 * M, -0.485 * M), (2.480 * M, -0.497 * M),
    (3.000 * M, -0.502 * M), (3.480 * M, -0.502 * M), (3.970 * M, -0.477 * M),
    (4.470 * M, -0.460 * M), (4.970 * M, -0.435 * M), (5.460 * M, -0.411 * M),
    (5.960 * M, -0.394 * M), (6.460 * M, -0.378 * M), (6.950 * M, -0.369 * M),
    (7.450 * M, -0.344 * M), (7.950 * M, -0.328 * M), (8.440 * M, -0.330 * M),
    (8.940 * M, -0.390 * M), (9.440 * M, -0.470 * M), (10.430 * M, -0.560 * M),
    (11.430 * M, -0.625 * M), (12.420 * M, -0.660 * M), (13.410 * M, -0.672 * M),
    (14.410 * M, -0.672 * M), (16.150 * M, -0.660 * M),
]
FOREBODY_BOT = _smooth(FOREBODY_BOT, 2)

# Nacelle radius.  Anchored on the measured outer walls: 1.706 at the inlet lip
# (axis 1.330 -> r 0.376 lateral, but the inlet is TALLER than wide so the
# section exponent and aspect below do the work), ~2.16 through the mid-body
# (axis 1.457 -> r 0.700, which also matches the rear view's nozzle ring), and
# ~2.06 at the exit.
# Lateral and vertical radii are kept SEPARATE because the nacelle section has
# to evolve from a tall rectangle at the inlet (0.76 m wide x 1.15 m high) to a
# true circle at the nozzle.  Driving that with one radius plus a fudge factor
# is what produces visible lofting artefacts along the nacelle.
NACELLE_RY = [
    (6.290 * M, 0.378 * M), (6.900 * M, 0.430 * M), (7.600 * M, 0.510 * M),
    (8.500 * M, 0.590 * M), (9.600 * M, 0.650 * M), (11.000 * M, 0.685 * M),
    (13.500 * M, 0.700 * M), (15.500 * M, 0.700 * M), (16.500 * M, 0.698 * M),
    (17.250 * M, 0.680 * M), (18.100 * M, 0.648 * M), (18.700 * M, 0.618 * M),
    (19.110 * M, 0.585 * M),
]

NACELLE_RZ = [
    (6.290 * M, 0.575 * M), (7.600 * M, 0.610 * M), (9.600 * M, 0.665 * M),
    (11.000 * M, 0.690 * M), (13.500 * M, 0.700 * M), (16.500 * M, 0.698 * M),
    (17.250 * M, 0.680 * M), (18.100 * M, 0.648 * M), (18.700 * M, 0.618 * M),
    (19.110 * M, 0.585 * M),
]

NACELLE_Z = [
    (6.290 * M, -0.055 * M), (8.000 * M, -0.045 * M), (10.000 * M, -0.030 * M),
    (12.000 * M, -0.020 * M), (14.000 * M, -0.010 * M), (16.000 * M, 0.000 * M),
    (19.110 * M, 0.000 * M),
]

# nacelle axis lateral offset -- the nacelles splay outward going aft
NACELLE_Y = [
    (6.290 * M, 1.330 * M), (9.000 * M, 1.372 * M), (12.000 * M, 1.418 * M),
    (15.000 * M, 1.446 * M), (17.250 * M, 1.457 * M), (19.110 * M, 1.457 * M),
]

# The flat tunnel between the nacelles.  Its deck sits a little BELOW the
# nacelle crowns (a broad shallow valley, not a plateau) and its belly is
# essentially FLUSH with the nacelle undersides -- which is why the underside of
# a Tomcat reads as one wide flat plate with two shallow humps rather than as
# two tubes with a bridge between them.
# The forward entries BRIDGE THE SPLITTER GAP.  Between the fuselage side
# (0.820 m) and the inlet inner cowl (0.950 m) the real aircraft is OPEN -- the
# boundary-layer diverter slot -- so a section taken there is genuinely two
# disconnected regions and cannot be lofted as one closed wire.  The body is
# therefore lofted with the slot FILLED and the slot is cut afterwards, which
# also gives it crisp machined walls instead of a lofted approximation.
PANCAKE_TOP = [
    (6.290 * M, 0.300 * M), (7.400 * M, 0.380 * M),
    (8.400 * M, 0.450 * M), (9.500 * M, 0.500 * M), (11.000 * M, 0.530 * M),
    (13.500 * M, 0.545 * M), (15.500 * M, 0.545 * M), (16.150 * M, 0.535 * M),
    (17.200 * M, 0.510 * M), (18.360 * M, 0.455 * M),
]

PANCAKE_BOT = [
    (6.290 * M, -0.400 * M), (7.400 * M, -0.520 * M),
    (8.400 * M, -0.620 * M), (9.500 * M, -0.672 * M), (11.000 * M, -0.700 * M),
    (13.500 * M, -0.706 * M), (15.500 * M, -0.700 * M), (16.150 * M, -0.690 * M),
    (17.200 * M, -0.660 * M), (18.360 * M, -0.580 * M),
]


def forebody(x):
    """(half_width, top_z, bottom_z) of the forebody lobe, absolute heights
    relative to the waterline.  None where the forebody no longer exists."""
    if x < -1.0 or x > 16.150 * M:
        return None
    return (_curve(FOREBODY_HALF_W, x),
            _curve(FOREBODY_TOP, x),
            _curve(FOREBODY_BOT, x))


def nacelle(x):
    """(y_offset, r_lateral, r_vertical, axis_z) or None outside the run."""
    if x < X_INLET_LIP or x > LENGTH:
        return None
    return (_curve(NACELLE_Y, x), _curve(NACELLE_RY, x),
            _curve(NACELLE_RZ, x), _curve(NACELLE_Z, x))


def canopy_lobe(x):
    """(half_width, top_z) of the canopy/spine lobe, or None outside its run.

    The body is lofted THROUGH the canopy's own outer surface; the cockpit
    module cuts the opening out of it and builds the transparency from the same
    functions, so the glass sits exactly on the surface it came from.
    """
    if x < CANOPY_HALF_W[0][0] or x > CANOPY_HALF_W[-1][0]:
        return None
    return (_curve(CANOPY_HALF_W, x), _curve(CANOPY_TOP, x))


def pancake(x):
    """(top_z, bottom_z) of the flat tunnel, or None outside its run."""
    if x < X_INLET_LIP or x > X_BEAVER_TIP:
        return None
    return (_curve(PANCAKE_TOP, x), _curve(PANCAKE_BOT, x))


# ---------------------------------------------------------------------------
# glove -- the fixed leading-edge structure that flows forward into the
# forward fuselage.  Its LE is a straight 70.5 deg line; the TE follows the
# wing seal.
# ---------------------------------------------------------------------------

GLOVE_LE_TAN = math.tan(math.radians(GLOVE_LE_SWEEP))
X_GLOVE_AFT = 13.000 * M       # aft of here the glove has merged into the body


def glove_le_x(y):
    """Station of the glove leading edge at lateral offset y.

    ``X_GLOVE_LE_ROOT`` is the line's CENTRELINE INTERCEPT, which is a
    construction point inside the radome, not where the glove starts.  The glove
    physically begins at the inlet cowl -- see :func:`glove_outer_y`.
    """
    return X_GLOVE_LE_ROOT + abs(y) * GLOVE_LE_TAN


X_GLOVE_FADE0 = 12.100 * M     # glove outer edge starts blending to the nacelle
X_GLOVE_FADE1 = 13.400 * M     # ... and has fully merged by here


def glove_te_x(y):
    """Station where the glove has faded into the nacelle/pancake behind it."""
    t = clamp(abs(y) / Y_GLOVE_OUTER, 0.0, 1.0)
    return lerp(X_GLOVE_AFT + 0.900 * M, X_GLOVE_FADE1, t)


GLOVE_HALF_T = 0.155 * M       # glove slab half-thickness once past the LE
GLOVE_EDGE_R = 0.130 * M       # radius of the rounded outboard seal edge


def glove_half_thickness(x, y):
    """Half-thickness of the glove sheet.

    Sharp at the leading edge, then essentially CONSTANT going aft.  It must
    not taper back to zero: the glove's aft boundary is not a trailing edge, it
    is where the glove disappears into the nacelle, and a chordwise taper there
    leaves a zero-thickness sliver sticking out past the nacelle that no loft
    can survive.  Outboard it closes with a rounded edge -- the wing seal -- so
    the section shuts tangentially instead of on a knife edge.
    """
    le, te = glove_le_x(y), glove_te_x(y)
    if x <= le or x >= te:
        return 0.0
    t = clamp((x - le) / max(te - le, 1.0), 0.0, 1.0)
    ramp = min(t / 0.22, 1.0) ** 0.55
    h = GLOVE_HALF_T * ramp * (1.0 - 0.18 * t)
    edge0 = Y_GLOVE_OUTER - GLOVE_EDGE_R
    if abs(y) > edge0:
        u = clamp((abs(y) - edge0) / GLOVE_EDGE_R, 0.0, 1.0)
        h *= math.sqrt(max(0.0, 1.0 - u * u))
    return h


GLOVE_Z = 0.135 * M            # glove mid-surface at the root, above the axis


def glove_camber_z(x, y):
    """Mid-surface height of the glove above the waterline.

    The glove carries the aircraft's dihedral: it rises slightly outboard and
    lifts a little going aft, which is what makes the top view read as a
    continuous surface rather than a plate stuck on the side of a tube.
    """
    rise = 0.075 * M * (abs(y) / Y_GLOVE_OUTER) ** 1.6
    aft = 0.040 * M * smoothstep(X_GLOVE_LE_ROOT, X_PIVOT, x)
    return GLOVE_Z + rise + aft


def glove_outer_y(x):
    """Outboard extent of the fixed glove at station x (0 where absent).

    The glove does NOT start at the cockpit.  Forward of the inlet the Tomcat's
    plan silhouette is just the forebody: the drawing's outer edge holds at
    0.807 m through x = 5 m, where a cockpit-rooted glove would already have
    pushed it out past 1.0 m.  The glove leading edge picks up at the inlet
    cowl's outer wall (6.63 m, 1.706 m) and runs aft at a constant 69.2 deg --
    that straight line is the Tomcat's signature, and it is why the planform
    widens steadily from a third of the way back rather than tapering.
    """
    if x < X_INLET_LIP or x > X_GLOVE_FADE1:
        return 0.0
    y_le = (x - X_GLOVE_LE_ROOT) / GLOVE_LE_TAN     # leading-edge limited
    limit = Y_GLOVE_OUTER
    if x > X_GLOVE_FADE0:
        # Aft of the seal the glove edge does not just stop -- that would leave
        # a step in the plan silhouette.  It blends into the nacelle's own outer
        # line, so the two become one edge.
        na = nacelle(x)
        target = (na[0] + na[1]) if na else Y_GLOVE_OUTER
        limit = lerp(Y_GLOVE_OUTER, target,
                     smoothstep(X_GLOVE_FADE0, X_GLOVE_FADE1, x))
    return clamp(min(y_le, limit), 0.0, Y_GLOVE_OUTER)


# ---------------------------------------------------------------------------
# wing pivot geometry
# ---------------------------------------------------------------------------


def wing_tip_xy(sweep_deg=SWEEP, side=1):
    """Wingtip position (x, y) for a commanded LE sweep."""
    ang = math.radians(sweep_deg + WING_TIP_PHI)
    return (X_PIVOT + WING_PIVOT_R * math.sin(ang),
            side * (Y_PIVOT + WING_PIVOT_R * math.cos(ang)))


def wing_semi_span(sweep_deg=SWEEP):
    return abs(wing_tip_xy(sweep_deg)[1])


def wing_span(sweep_deg=SWEEP):
    return 2.0 * wing_semi_span(sweep_deg)


# ---------------------------------------------------------------------------
# convenience: waterline-relative -> world Z
# ---------------------------------------------------------------------------


def wz(z_rel, x=None):
    """World Z for a waterline-relative height, including the ground pitch."""
    z = WATERLINE + z_rel
    if x is not None and GROUND_PITCH:
        z += (x - X_MAIN_GEAR) * math.tan(math.radians(GROUND_PITCH))
    return z


def report():
    """Print the derived envelope so the numbers can be checked against spec."""
    lines = [
        f"length            {LENGTH/M:8.3f} m   (spec 19.110)",
        f"span @ {SWEEP:.0f} deg      {wing_span(SWEEP)/M:8.3f} m   (spec {SPAN_20/M:.3f})",
        f"span @ 68 deg     {wing_span(68)/M:8.3f} m   (spec {SPAN_68/M:.3f})",
        f"span @ 75 deg     {wing_span(75)/M:8.3f} m   (spec {SPAN_75/M:.3f})",
        f"stabilator span   {STAB_SPAN/M:8.3f} m",
        f"wheelbase         {WHEELBASE/M:8.3f} m",
        f"main track        {MAIN_TRACK/M:8.3f} m",
        f"inlet outer wall  {Y_INLET_OUTER/M:8.3f} m",
        f"wingtip @ {SWEEP:.0f} deg   x={wing_tip_xy(SWEEP)[0]/M:.3f} m  y={wing_tip_xy(SWEEP)[1]/M:.3f} m",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(report())
