"""Full-width body sections for the F-14D blended airframe.

At every station one closed section is generated by SMOOTHLY BLENDING the
component volumes that exist there.  That is what makes the glove flow into the
forward fuselage, the nacelle flow into the pancake, and the fin root sit on a
continuous surface -- none of those transitions is a fillet, and none of them is
a join.  Lofting these sections produces the whole airframe skin as one solid.

Section convention: a list of (y, z) pairs in the station plane, wound
counter-clockwise when viewed from the front (+X), closed implicitly.  z is
relative to the waterline; the loft lifts it to world Z.
"""

from __future__ import annotations

import math

from lib import geometry as G

BIG = 1.0e7

# Where the one-piece skin loft STOPS.  Aft of the beavertail the pancake is
# gone and a station cuts the two nacelles as two separate closed regions --
# genuinely not one wire, so not one loft.  The nozzle module picks it up from
# here, which is also the real structural break: the nozzle shrouds are bolted
# to the engine bay, not part of the fuselage skin.
X_SKIN_AFT = 18.300 * G.M


def _superellipse_top(dy, half_w, height, n):
    """Top of a superellipse of half-width ``half_w`` and half-height
    ``height``, at lateral distance ``dy`` from its axis.  None when outside.

    ``t`` is clamped just inside 1 rather than rejected at exactly 1, so a
    sample landing precisely on the silhouette returns 0 instead of dropping
    out.  Dropped samples make section point counts vary station to station,
    which is what makes a multi-section loft fail.
    """
    if half_w <= 1e-6 or height <= 1e-6:
        return None
    t = abs(dy) / half_w
    if t > 1.0 + 1e-9:
        return None
    t = min(t, 1.0)
    return height * (1.0 - t ** n) ** (1.0 / n)


def _forebody(x, y):
    """(top, bottom) of the forebody lobe at (x, y), or (None, None).

    Top and bottom are shaped independently about the section's mid-height so
    the keel can be flatter than the crown, which is what the real forebody
    does under the cockpit.
    """
    fb = G.forebody(x)
    if fb is None:
        return None, None
    hw, zt, zb = fb
    zc = 0.5 * (zt + zb)
    # near-circular at the radome, squaring off aft as it becomes the tunnel
    n_up = G.lerp(2.0, 2.7, G.smoothstep(2.0 * G.M, 10.0 * G.M, x))
    n_lo = G.lerp(2.1, 3.6, G.smoothstep(2.0 * G.M, 9.0 * G.M, x))
    up = _superellipse_top(y, hw, zt - zc, n_up)
    dn = _superellipse_top(y, hw, zc - zb, n_lo)
    return (None if up is None else zc + up,
            None if dn is None else zc - dn)


def _nacelle(x, y, side):
    """(top, bottom) of one nacelle lobe."""
    na = G.nacelle(x)
    if na is None:
        return None, None
    yn, r_lat, r_ver, zc = na
    dy = y - side * yn
    # The nacelle cross-section EVOLVES: a rounded rectangle at the inlet
    # (exponent 3.6, tall and narrow) that becomes a true circle by the nozzle.
    # Doing this in the section maths -- rather than lofting a box body into a
    # round one -- is what keeps the nacelle free of lofting artefacts.
    t = G.smoothstep(G.X_INLET_LIP, G.X_NOZZLE_START, x)
    n = G.lerp(3.6, 2.0, t)
    up = _superellipse_top(dy, r_lat, r_ver, n)
    return (None if up is None else zc + up,
            None if up is None else zc - up)


def _pancake(x, y):
    """(top, bottom) of the flat tunnel between the nacelles."""
    pk = G.pancake(x)
    if pk is None:
        return None, None
    zt, zb = pk
    na = G.nacelle(x)
    span = (na[0] if na else G.Y_NACELLE) * 1.00
    if abs(y) > span:
        return None, None
    # a whisper of camber so the deck is not a dead flat plane
    c = 1.0 - 0.10 * (abs(y) / span) ** 2
    return zt * c, zb * c


def _glove(x, y):
    """(top, bottom) of the fixed glove sheet.

    At zero thickness this returns the mid-surface for BOTH faces rather than
    None: the sample belongs to the section (it is the knife edge), and
    dropping it is what made stations disagree on point count.
    """
    outer = G.glove_outer_y(x)
    if outer <= 1e-6 or abs(y) > outer:
        return None, None
    ht = G.glove_half_thickness(x, y)
    z = G.glove_camber_z(x, y)
    return z + ht, z - ht


def _canopy(x, y):
    """(top, bottom) of the canopy/spine lobe.  Contributes a TOP only -- it is
    a bubble sitting on the deck, not a body with an underside."""
    cl = G.canopy_lobe(x)
    if cl is None:
        return None, None
    hw, top = cl
    fb = G.forebody(x)
    base = fb[1] if fb else 0.0
    up = _superellipse_top(y, hw, max(top - base, 1.0), 2.15)
    return (None if up is None else base + up, None)


def outer_half_width(x):
    """Overall half-width of the airframe skin at station x."""
    w = 0.0
    fb = G.forebody(x)
    if fb:
        w = max(w, fb[0])
    na = G.nacelle(x)
    if na:
        w = max(w, na[0] + na[1])
    w = max(w, G.glove_outer_y(x))
    return w


def _blend_radius(x):
    """How wide the smooth transitions are at this station.

    Tight up front where the forebody is a crisp shape; WIDE through the inlet
    and glove junctions, where the aircraft has to read as one surface and
    where a narrow blend leaves a curvature spike the loft turns into a visible
    crease.  With the polynomial smooth-max these widths cost at most k/4 of
    added material and buy curvature bounded by 1/k.
    """
    return G.lerp(0.060 * G.M, 0.460 * G.M,
                  G.smoothstep(3.2 * G.M, 8.0 * G.M, x))


def surfaces(x, y):
    """Blended (top, bottom) of the airframe skin at (x, y).

    Returns (None, None) where no component exists.
    """
    k = _blend_radius(x)
    tops, bots = [], []
    for get in (lambda: _forebody(x, y),
                lambda: _nacelle(x, y, +1),
                lambda: _nacelle(x, y, -1),
                lambda: _pancake(x, y),
                lambda: _glove(x, y),
                lambda: _canopy(x, y)):
        t, b = get()
        if t is not None:
            tops.append(t)
        if b is not None:
            bots.append(b)
    if not tops and not bots:
        return None, None
    top = G.smax_all(tops, k) if tops else None
    bot = G.smin_all(bots, k) if bots else None
    if top is None:
        top = bot
    if bot is None:
        bot = top
    return top, bot


def rails(x):
    """Lateral positions of the section's FEATURE LINES, always increasing.

    A loft matches its sections POINT BY INDEX.  Sampling each station by
    y/half-width means a feature -- the nacelle crest, the glove edge -- sits at
    a different index at every station, because the half-width changes; the
    surface then twists between stations and the whole aft body reads as
    crumpled foil.  Pinning the samples to rails that follow the features makes
    index i mean the same thing at every station, which is what a lofted
    aircraft surface needs.

    Where a component does not exist yet the rail is interpolated across the
    remaining width, so the rails stay strictly increasing and never collapse.
    """
    w = outer_half_width(x)
    fb = G.forebody(x)
    na = G.nacelle(x)
    r1 = min(fb[0], w * 0.92) if fb else w * 0.35
    if na:
        r2 = na[0]                      # nacelle axis
        r3 = min(na[0] + na[1], w)      # nacelle outer silhouette
    else:
        r2 = r1 + (w - r1) * 0.45
        r3 = r1 + (w - r1) * 0.80
    # keep them ordered and separated
    gap = max(w * 0.012, 6.0)
    r1 = G.clamp(r1, gap, w - 3 * gap)
    r2 = G.clamp(r2, r1 + gap, w - 2 * gap)
    r3 = G.clamp(r3, r2 + gap, w - gap)
    return 0.0, r1, r2, r3, w


# points allocated to each rail-to-rail band of the starboard half
BANDS = (12, 9, 14, 12)


def half_samples(x, n=None):
    """Starboard-half y samples, distributed band by band between the rails.

    Every band is cosine-eased at BOTH ends so samples crowd the rails.  The
    rails are exactly where the surface turns hardest -- the nacelle crest, the
    nacelle silhouette where the glove overhangs it -- so spacing points evenly
    inside a band leaves the sharpest part of the curve the worst resolved.
    """
    r0, r1, r2, r3, w = rails(x)
    out = [0.0]
    for (a, b), count in zip(((r0, r1), (r1, r2), (r2, r3), (r3, w)), BANDS):
        for i in range(1, count + 1):
            t = 0.5 - 0.5 * math.cos(math.pi * i / count)
            out.append(a + (b - a) * t)
    return out


def section_curves(x, n=52):
    """(top, bottom) point lists for station x, sharing both end points.

    Kept separate so the wire can be built as TWO splines meeting at the two
    lateral silhouette points.  A single periodic spline through the whole
    section would round those corners off, and they are genuinely sharp -- the
    glove edge and the wing seal are knife edges, not radii.
    """
    w = outer_half_width(x)
    if w <= 1e-6:
        return [], []
    # Evaluate the STARBOARD half only and mirror it.  Bilateral symmetry then
    # holds to the last bit by construction, instead of depending on the
    # blending maths landing on identical floats for +y and -y.
    right = []
    last = None
    for y in half_samples(x, n):
        t, b = surfaces(x, y)
        if t is None:
            if last is None:
                t = b = 0.0
            else:
                t, b = last
        if t < b:
            t = b = 0.5 * (t + b)
        last = (t, b)
        right.append((y, t, b))
    # pinch the outboard silhouette point so the wire closes to a real edge
    y_e, t_e, b_e = right[-1]
    mid = 0.5 * (t_e + b_e)
    right[-1] = (y_e, mid, mid)
    left = [(-y, t, b) for y, t, b in reversed(right[1:])]
    full = left + right
    top = [(y, t) for y, t, _ in full]
    bot = [(y, b) for y, _, b in full]
    return top, bot


def section_points(x, n=52):
    """Closed section at station x as (y, z) pairs, wound CCW seen from +X.

    Points run across the top from starboard (-Y) to port (+Y), then back
    across the bottom.  The ends are pinched to the silhouette so the wire
    closes cleanly instead of leaving a blunt sliver.
    """
    w = outer_half_width(x)
    if w <= 1e-6:
        return []
    # cosine spacing: dense at the two silhouette edges where curvature is worst
    ys = [-w * math.cos(math.pi * i / (n - 1)) for i in range(n)]
    top, bot = [], []
    for y in ys:
        t, b = surfaces(x, y)
        if t is None:
            continue
        if t < b:
            t = b = 0.5 * (t + b)
        top.append((y, t))
        bot.append((y, b))
    if len(top) < 4:
        return []
    # pinch the extreme edges together so the profile closes to a real edge
    ymin, ymax = top[0][0], top[-1][0]
    zt0, zb0 = top[0][1], bot[0][1]
    zt1, zb1 = top[-1][1], bot[-1][1]
    top[0] = (ymin, 0.5 * (zt0 + zb0))
    bot[0] = (ymin, 0.5 * (zt0 + zb0))
    top[-1] = (ymax, 0.5 * (zt1 + zb1))
    bot[-1] = (ymax, 0.5 * (zt1 + zb1))
    return top + list(reversed(bot[1:-1]))


# ---------------------------------------------------------------------------
# station list -- denser where the shape changes fastest
# ---------------------------------------------------------------------------


def stations():
    """The x stations the skin is lofted through."""
    key = [
        (0.0, 0.130 * G.M),                       # radome tip: dense
        (0.60 * G.M, 0.260 * G.M),
        (2.00 * G.M, 0.400 * G.M),
        (3.40 * G.M, 0.320 * G.M),                # windscreen
        (5.00 * G.M, 0.260 * G.M),                # canopy
        (6.10 * G.M, 0.120 * G.M),                # inlet lip: dense, the shape
        (6.55 * G.M, 0.240 * G.M),                # changes fastest here
        (8.20 * G.M, 0.320 * G.M),
        (9.20 * G.M, 0.420 * G.M),
        (11.00 * G.M, 0.520 * G.M),
        (13.50 * G.M, 0.520 * G.M),
        (15.80 * G.M, 0.360 * G.M),
        (16.90 * G.M, 0.220 * G.M),               # beavertail
        (X_SKIN_AFT, 0.0),
    ]
    xs, x = [0.0], 0.0
    i = 0
    while x < X_SKIN_AFT - 1e-6:
        while i < len(key) - 1 and x >= key[i + 1][0]:
            i += 1
        step = key[i][1]
        if i < len(key) - 1 and key[i + 1][1] > 0:
            t = (x - key[i][0]) / max(key[i + 1][0] - key[i][0], 1.0)
            step = G.lerp(key[i][1], key[i + 1][1], G.clamp(t, 0.0, 1.0))
        x = min(x + step, X_SKIN_AFT)
        xs.append(x)
    return xs


if __name__ == "__main__":
    xs = stations()
    print(f"{len(xs)} stations, {xs[0]:.1f} .. {xs[-1]:.1f} mm")
    for x in (0.2 * G.M, 1.5 * G.M, 3.5 * G.M, 5.5 * G.M, 6.5 * G.M,
              8.0 * G.M, 10.0 * G.M, 13.0 * G.M, 16.0 * G.M, 18.0 * G.M,
              19.0 * G.M):
        pts = section_points(x)
        w = outer_half_width(x)
        zs = [p[1] for p in pts]
        print(f"x={x/G.M:6.2f} m  pts={len(pts):3d}  halfwidth={w/G.M:5.3f} "
              f"z {min(zs)/G.M:+6.3f}..{max(zs)/G.M:+6.3f}")
