"""Encoder + collation parity against a fixture generated by Node.

``golden/golden.json`` is produced by ``golden/gen_golden.mjs``, which uses only
the JavaScript LANGUAGE — ``encodeURIComponent``, ``URLSearchParams``,
``BigInt.prototype.toString(36)``, ``decodeURIComponent``, ``new URL()`` and a
cached ``Intl.Collator``. It imports nothing from ``server/``, so the oracle
cannot drift into agreement with a bug on either side.

Regenerate with::

    node tests/python/packages/cadgen/viewer/golden/gen_golden.mjs
"""

from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

from cadgen.viewer import encoding, natural_sort, url_norm

GOLDEN_PATH = Path(__file__).resolve().parent / "golden" / "golden.json"
# encoding="utf-8" is load-bearing: a Windows runner's cp1252 default once
# decoded the fixture differently and the encoders got blamed for it.
GOLDEN = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))

# Corpus rows whose position the model gets wrong. EMPTY, and it must stay
# empty: the contraction pass in gen_golden.mjs removed the Arabic
# presentation-form class that a per-character model could not express, and the
# corpus deliberately sweeps that whole block to prove it. Adding an entry here
# is a decision to ship a known misordering, not a way to make a test pass.
KNOWN_SORT_RESIDUE: frozenset[str] = frozenset()


class EncodeUriComponent(unittest.TestCase):
    def test_matches_node(self) -> None:
        for value, expected in GOLDEN["encodeUriComponent"]:
            with self.subTest(value=value):
                self.assertEqual(encoding.encode_uri_component(value), expected)

    def test_url_path_matches_node(self) -> None:
        for value, expected in GOLDEN["encodeUrlPath"]:
            with self.subTest(value=value):
                self.assertEqual(encoding.encode_url_path(value), expected)

    def test_quote_default_would_have_been_wrong(self) -> None:
        # Guards the comment in encoding.py: urllib's default is wrong in BOTH
        # directions, so nobody "simplifies" this back to quote(value).
        from urllib.parse import quote

        self.assertNotEqual(quote("a!*'()/b"), encoding.encode_uri_component("a!*'()/b"))


class Base36(unittest.TestCase):
    def test_values(self) -> None:
        for value, expected in GOLDEN["base36"]:
            with self.subTest(value=value):
                self.assertEqual(encoding.base36(int(value)), expected)

    def test_file_version(self) -> None:
        for size, mtime_ns, expected in GOLDEN["fileVersion"]:
            with self.subTest(size=size, mtime_ns=mtime_ns):
                self.assertEqual(encoding.file_version(int(size), int(mtime_ns)), expected)


class FormEncoding(unittest.TestCase):
    def test_url_search_params(self) -> None:
        for pairs, expected in GOLDEN["formEncode"]:
            with self.subTest(pairs=pairs):
                self.assertEqual(encoding.form_encode([(k, v) for k, v in pairs]), expected)

    def test_star_stays_literal_and_tilde_does_not(self) -> None:
        self.assertEqual(encoding.form_encode([("a", "*~ ")]), "a=*%7E+")

    def test_quote_plus_would_have_been_wrong(self) -> None:
        from urllib.parse import quote_plus

        self.assertNotEqual(quote_plus("*~"), encoding.form_encode([("a", "*~")]).split("=")[1])

    @unittest.skipIf(sys.platform.startswith("win"), "POSIX absolute paths are drive-relative on Windows")
    def test_local_asset_url(self) -> None:
        for file_path, version, expected in GOLDEN["localAssetUrl"]:
            with self.subTest(file_path=file_path):
                self.assertEqual(encoding.local_asset_url_for_path(file_path, version), expected)


class StrictDecode(unittest.TestCase):
    def test_matches_node_including_the_throws(self) -> None:
        for value, outcome in GOLDEN["strictDecode"]:
            with self.subTest(value=value):
                if outcome["ok"]:
                    self.assertEqual(encoding.strict_decode_uri_component(value), outcome["value"])
                else:
                    with self.assertRaises(encoding.UriError):
                        encoding.strict_decode_uri_component(value)

    def test_the_three_throw_classes_are_all_covered_by_the_fixture(self) -> None:
        throwing = {value for value, outcome in GOLDEN["strictDecode"] if not outcome["ok"]}
        self.assertIn("%zz", throwing, "malformed escape")
        self.assertIn("%C0%AF", throwing, "overlong UTF-8")
        self.assertIn("%ED%A0%80", throwing, "lone surrogate")

    def test_unquote_would_have_been_wrong(self) -> None:
        from urllib.parse import unquote

        # unquote raises for none of the three; that silence is the bug.
        self.assertEqual(unquote("%zz"), "%zz")


class UrlNormalisation(unittest.TestCase):
    def test_pathname_matches_whatwg(self) -> None:
        for target, expected in GOLDEN["urlPathname"]:
            with self.subTest(target=target):
                self.assertEqual(url_norm.request_pathname(target), expected)

    def test_dot_segments_leave_the_api_namespace(self) -> None:
        # Routing on urlsplit().path would send this into the /__cad/ dispatch.
        self.assertEqual(url_norm.request_pathname("/__cad/../etc/passwd"), "/etc/passwd")
        self.assertEqual(url_norm.request_pathname("/__cad/%2e%2e/etc"), "/etc")

    def test_percent_2f_is_not_a_separator(self) -> None:
        self.assertEqual(
            url_norm.request_pathname("/__tess_cache/%2e%2e%2fescape.tess"),
            "/__tess_cache/%2e%2e%2fescape.tess",
        )

    def test_path_percent_encode_set(self) -> None:
        for byte, expected in GOLDEN["pathPercentEncodeSet"]:
            if expected is None:
                continue
            target = "/p" + chr(byte) + "q"
            with self.subTest(byte=byte):
                self.assertEqual(url_norm.request_pathname(target), expected)


class QueryParsing(unittest.TestCase):
    def test_matches_url_search_params_get(self) -> None:
        for target, expectations in GOLDEN["urlQuery"]:
            query = url_norm.request_query(target)
            for key, expected in expectations:
                with self.subTest(target=target, key=key):
                    self.assertEqual(query.get(key), expected)

    def test_repeated_params_take_the_first(self) -> None:
        query = url_norm.request_query("/x?file=/tmp/x&file=/etc/passwd")
        self.assertEqual(query.get("file"), "/tmp/x")

    def test_blank_values_are_kept(self) -> None:
        # keep_blank_values=False would answer "z" here — a real hole.
        query = url_norm.request_query("/x?file=&v=1&file=z")
        self.assertEqual(query.get("file"), "")


class NaturalSort(unittest.TestCase):
    def test_reproduces_the_golden_order(self) -> None:
        corpus = GOLDEN["sortCorpus"]
        golden = GOLDEN["sortGolden"]
        ours = sorted(corpus, key=natural_sort.collation_key)
        if ours == golden:
            return
        misplaced = {a for a, b in zip(ours, golden) if a != b} | {
            b for a, b in zip(ours, golden) if a != b
        }
        unexpected = misplaced - KNOWN_SORT_RESIDUE
        self.assertEqual(
            unexpected,
            set(),
            f"{len(unexpected)} corpus rows sort differently from V8 and are not known residue",
        )

    def test_known_residue_does_not_grow(self) -> None:
        corpus = GOLDEN["sortCorpus"]
        golden = GOLDEN["sortGolden"]
        ours = sorted(corpus, key=natural_sort.collation_key)
        mismatches = sum(1 for a, b in zip(ours, golden) if a != b)
        self.assertLessEqual(mismatches, len(KNOWN_SORT_RESIDUE) * 2)

    def test_pairwise_sign_matrix(self) -> None:
        subset = GOLDEN["sortPairSubset"]
        signs = GOLDEN["sortPairSigns"]
        keys = [natural_sort.collation_key(value) for value in subset]
        index = 0
        failures = []
        for i, key_a in enumerate(keys):
            for j, key_b in enumerate(keys):
                expected = signs[index]
                index += 1
                actual = (key_a > key_b) - (key_a < key_b)
                if actual != expected:
                    failures.append((subset[i], subset[j], expected, actual))
        self.assertEqual(failures[:20], [], f"{len(failures)} of {index} ordered pairs disagree")

    def test_an_ignorable_between_two_digits_terminates_the_run(self) -> None:
        # The correction this whole module is shaped around. Every one of these
        # is 0 under a "drop ignorables, then tokenise" implementation.
        key = natural_sort.collation_key
        self.assertLess(key("1\u00ad2"), key("12"))
        self.assertGreater(key("11"), key("1\u00ad1"))
        self.assertGreater(key("2"), key("1\u00ad1"))
        for ignorable in ("\u00ad", "\u200b", "\u0301", "\ufe0f"):
            with self.subTest(ignorable=repr(ignorable)):
                self.assertLess(key("1" + ignorable + "2"), key("12"))
        # ...while letters are unaffected.
        self.assertEqual(key("ab"), key("a\u00adb"))

    def test_the_corpus_actually_contains_that_class(self) -> None:
        # Without generated digit+ignorable rows the 160,000-pair matrix stays
        # green while the bug ships. Prove the generator emitted them.
        corpus = GOLDEN["sortCorpus"]
        self.assertIn("1\u00ad2", corpus)
        self.assertIn("12", corpus)

    def test_contractions_are_not_collapsed_to_their_base(self) -> None:
        # ARABIC HAMZA ABOVE is L1-ignorable ALONE, but ALEF + HAMZA ABOVE is a
        # contraction with its own primary weight. A model that drops the mark
        # collapses every hamza/madda/wasla variant onto plain alef.
        key = natural_sort.collation_key
        alef = "\u0627"            # ARABIC LETTER ALEF
        hamza_above = "\u0654"     # ARABIC HAMZA ABOVE
        alef_hamza = "\u0623"      # ALEF WITH HAMZA ABOVE
        alef_hamza_below = "\u0625"
        wasla = "\u0671"           # ALEF WASLA
        self.assertEqual(key(hamza_above), [], "the mark alone carries no weight")
        # ...yet the pair does, and it is its own weight, not alef's.
        self.assertEqual(key(alef + hamza_above), key(alef_hamza))
        self.assertNotEqual(key(alef_hamza), key(alef))
        # Four distinct primaries where a mark-dropping model produces one.
        weights = {
            key(alef)[0],
            key(alef_hamza)[0],
            key(alef_hamza_below)[0],
            key(wasla)[0],
        }
        self.assertEqual(len(weights), 4)
        # Presentation forms expand onto those same contractions.
        self.assertEqual(key("\ufe84"), key(alef_hamza))  # ALEF WITH HAMZA ABOVE FINAL
        self.assertEqual(key("\ufb50"), key(wasla))       # ALEF WASLA ISOLATED
        self.assertNotEqual(key("a\ufe84"), key("a\ufb50"))

    def test_no_contraction_starts_with_a_digit(self) -> None:
        # The walker tries contractions before digit runs; if a digit could
        # begin one, the digit-run scan would need to stop at it too.
        table = natural_sort._table()  # noqa: SLF001
        zero = table.zero_bucket
        for sequence in table.contractions:
            bucket = table.bucket(ord(sequence[0]))
            self.assertFalse(zero <= bucket <= zero + 9, sequence)

    def test_documented_semantics(self) -> None:
        key = natural_sort.collation_key
        self.assertEqual(key("v2.9.step") < key("v2.10.step"), True)
        self.assertEqual(key("v2.10.step") < key("v10.1.step"), True)
        self.assertEqual(key("a.step"), key("A.step"))
        self.assertEqual(key("e.step"), key("é.step"))
        self.assertEqual(key("a01"), key("a1"))
        self.assertEqual(key("a001"), key("a1"))
        self.assertEqual(key("ß"), key("ss"))
        self.assertEqual(key("æ"), key("ae"))
        self.assertEqual(key("Ⅻ"), key("xii"))
        self.assertEqual(key("Ａ"), key("a"))
        self.assertEqual(key("１"), key("1"))
        self.assertNotEqual(key("①"), key("1"))
        self.assertNotEqual(key("²"), key("2"))
        self.assertLess(key("_x.step"), key("9.step"))
        self.assertLess(key(""), key("a"))
        self.assertLess(key("a"), key("a0"))
        # Arbitrary precision, not float or int64.
        self.assertLess(key("a" + "9" * 80), key("a" + "1" + "0" * 80))

    def test_sort_catalog_entries_is_non_mutating_and_coerces(self) -> None:
        entries = [{"file": "b"}, {"file": None}, {"file": "a"}, {}, {"file": 0}]
        original = list(entries)
        result = natural_sort.sort_catalog_entries(entries)
        self.assertEqual(entries, original)
        self.assertEqual([e.get("file") for e in result[:3]], [None, None, 0])
        self.assertEqual([e.get("file") for e in result[3:]], ["a", "b"])


class ShippedCollationTable(unittest.TestCase):
    def test_the_shipped_table_is_the_one_the_fixture_was_built_from(self) -> None:
        # A stale collation.json would serve a different catalog order with no
        # other symptom. This is the only thing that catches it.
        self.assertTrue(natural_sort.COLLATION_PATH.is_file())
        ours = sorted(GOLDEN["sortCorpus"], key=natural_sort.collation_key)
        mismatches = sum(1 for a, b in zip(ours, GOLDEN["sortGolden"]) if a != b)
        self.assertLessEqual(mismatches, len(KNOWN_SORT_RESIDUE) * 2)

    def test_table_shape(self) -> None:
        payload = json.loads(natural_sort.COLLATION_PATH.read_text(encoding="utf-8"))
        self.assertEqual(payload["schemaVersion"], 1)
        self.assertEqual(payload["collatorOptions"], {"numeric": True, "sensitivity": "base"})
        self.assertGreater(len(payload["bucketRuns"]), 1000)
        self.assertGreater(len(payload["expansions"]), 1000)
        # Tab/LF/CR are NOT ignorable; a blanket "drop category Cc" is wrong.
        table = natural_sort._table()  # noqa: SLF001
        for char in "\t\n\v\f\r\u0085 ":
            self.assertFalse(table.is_ignorable(ord(char)), repr(char))
        for char in "\x00\x08\u00ad\u200b\u0301":
            self.assertTrue(table.is_ignorable(ord(char)), repr(char))


if __name__ == "__main__":
    unittest.main()
